// <auto-generated>
//     This code was generated by the ModernUO Serialization Generator tool.
//     Version: {VERSION}
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

#pragma warning disable

namespace TestContent
{
    [System.CodeDom.Compiler.GeneratedCode("ModernUO.Serialization.Generator", "{VERSION}")]
    public partial class ExternalItem
    {
        private const int SerializationVersion = 1;

        public string Name
        {
            get => _name;
            set
            {
                if (value != _name)
                {
                    _name = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public Server.Timer RefreshTimer
        {
            get => _refreshTimer;
            set
            {
                if (value != _refreshTimer)
                {
                    _refreshTimer = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public ExternalItem(Server.Serial serial)
        {
            Serial = serial;
        }

        ref struct V0Content
        {
            internal readonly string Name;
            internal V0Content(Server.IGenericReader reader, TestContent.ExternalItem entity)
            {
                Name = reader.ReadString();
            }
        }

        public virtual void Serialize(Server.IGenericWriter writer)
        {
            writer.WriteEncodedInt(SerializationVersion);

            writer.Write(_name);

            writer.WriteAnchoredTime(RefreshTimer?.Next ?? System.DateTime.MinValue);
        }

        public virtual void Deserialize(Server.IGenericReader reader)
        {
            var version = reader.ReadEncodedInt();

            if (version == 0)
            {
                MigrateFrom(new V0Content(reader, this));
                Server.ISerializableExtensions.MarkDirty(this);
                ValidateState();
                Server.Timer.DelayCall(RebuildCaches);
                return;
            }

            _name = reader.ReadString();

            var RefreshTimerNext = reader.ReadAnchoredTime();
            var RefreshTimerDelay = RefreshTimerNext == System.DateTime.MinValue ? System.TimeSpan.MinValue : RefreshTimerNext - Server.Core.Now;
            if (RefreshTimerNext != System.DateTime.MinValue)
            {
                DeserializeRefreshTimer(RefreshTimerDelay);
            }
            ValidateState();
            Server.Timer.DelayCall(RebuildCaches);
        }
    }
}
