// <auto-generated>
//     This code was generated by the ModernUO Serialization Generator tool.
//     Version: {VERSION}
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

#pragma warning disable

namespace Server.TestContent
{
    [System.CodeDom.Compiler.GeneratedCode("ModernUO.Serialization.Generator", "{VERSION}")]
    public partial class FieldModifiersItem
    {
        private const int SerializationVersion = 0;

        public string Description
        {
            get => _description;
            set
            {
                if (value != _description)
                {
                    _description = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public System.Collections.Generic.Dictionary<int, string> Entries
        {
            get => _entries;
            set
            {
                if (value != _entries)
                {
                    _entries = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public void AddToEntries(int key, string value)
        {
            Entries.Add(key, value);
            Server.ISerializableExtensions.MarkDirty(this);
        }

        public void RemoveFromEntries(int key)
        {
            Entries.Remove(key);
            Server.ISerializableExtensions.MarkDirty(this);
        }

        public void ReplaceInEntries(int key, string value)
        {
            Entries[key] = value;
            Server.ISerializableExtensions.MarkDirty(this);
        }

        public void ClearEntries()
        {
            Entries.Clear();
            Server.ISerializableExtensions.MarkDirty(this);
        }

        public int Level
        {
            get => _level;
            set
            {
                var oldValue = _level;
                if (value != _level)
                {
                    _level = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                    InvalidateProperties();
                    OnLevelChanged(oldValue, value);
                }
            }
        }

        public FieldModifiersItem(Server.Serial serial)
        {
            Serial = serial;
        }

        public virtual void Serialize(Server.IGenericWriter writer)
        {
            writer.WriteEncodedInt(SerializationVersion);

            writer.Write(_description);

            _entries?.Tidy();
            var _entriesCount = _entries?.Count ?? 0;
            writer.WriteEncodedInt(_entriesCount);
            if (_entriesCount > 0)
            {
                foreach (var (_entriesKey, _entriesValue) in _entries!)
                {
                    writer.Write(_entriesKey);
                    writer.Write(_entriesValue);
                }
            }

            writer.Write(_level);
        }

        public virtual void Deserialize(Server.IGenericReader reader)
        {
            var version = reader.ReadEncodedInt();

            _description = reader.ReadString();

            int _entriesKey;
            string _entriesValue;
            var _entriesCount = reader.ReadEncodedInt();
            _entries = new System.Collections.Generic.Dictionary<int, string>(_entriesCount);
            for (var _entriesIndex = 0; _entriesIndex < _entriesCount; _entriesIndex++)
            {
                _entriesKey = reader.ReadInt();
                _entriesValue = reader.ReadString();
                if (typeof(int).IsValueType || _entriesKey != default)
                {
                    _entries.Add(_entriesKey, _entriesValue);
                }
            }

            _level = reader.ReadInt();
        }
    }
}
