// <auto-generated>
//     This code was generated by the ModernUO Serialization Generator tool.
//     Version: {VERSION}
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

#pragma warning disable

namespace Server.TestContent
{
    [System.CodeDom.Compiler.GeneratedCode("ModernUO.Serialization.Generator", "{VERSION}")]
    public partial class TrackedChild
    {
        private const int SerializationVersion = 0;

        public virtual void MarkDirty()
        {
            Server.ISerializableExtensions.MarkDirty(_owner);
        }

        public Server.Timer RefreshTimer
        {
            get => _refreshTimer;
            set
            {
                if (value != _refreshTimer)
                {
                    _refreshTimer = value;
                    MarkDirty();
                }
            }
        }

        public int Progress
        {
            get => _progress;
            set
            {
                if (value != _progress)
                {
                    _progress = value;
                    MarkDirty();
                }
            }
        }

        public virtual void Serialize(Server.IGenericWriter writer)
        {
            writer.Write(SerializationVersion);

            writer.Write(RefreshTimer?.Next ?? System.DateTime.MinValue);

            writer.Write(_progress);
        }

        public virtual void Deserialize(Server.IGenericReader reader)
        {
            var version = reader.ReadInt();

            var RefreshTimerNext = reader.ReadDateTime();
            var RefreshTimerDelay = RefreshTimerNext == System.DateTime.MinValue ? System.TimeSpan.MinValue : RefreshTimerNext - Server.Core.Now;
            DeserializeRefreshTimer(RefreshTimerDelay);

            _progress = reader.ReadInt();
        }
    }
}
