// <auto-generated>
//     This code was generated by the ModernUO Serialization Generator tool.
//     Version: {VERSION}
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

#pragma warning disable

namespace Server.TestContent
{
    [System.CodeDom.Compiler.GeneratedCode("ModernUO.Serialization.Generator", "{VERSION}")]
    public partial class UlongFlagsItem
    {
        private const int SerializationVersion = 0;

        public string Field0
        {
            get => _field0;
            set
            {
                if (value != _field0)
                {
                    _field0 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field1
        {
            get => _field1;
            set
            {
                if (value != _field1)
                {
                    _field1 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field2
        {
            get => _field2;
            set
            {
                if (value != _field2)
                {
                    _field2 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field3
        {
            get => _field3;
            set
            {
                if (value != _field3)
                {
                    _field3 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field4
        {
            get => _field4;
            set
            {
                if (value != _field4)
                {
                    _field4 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field5
        {
            get => _field5;
            set
            {
                if (value != _field5)
                {
                    _field5 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field6
        {
            get => _field6;
            set
            {
                if (value != _field6)
                {
                    _field6 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field7
        {
            get => _field7;
            set
            {
                if (value != _field7)
                {
                    _field7 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field8
        {
            get => _field8;
            set
            {
                if (value != _field8)
                {
                    _field8 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field9
        {
            get => _field9;
            set
            {
                if (value != _field9)
                {
                    _field9 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field10
        {
            get => _field10;
            set
            {
                if (value != _field10)
                {
                    _field10 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field11
        {
            get => _field11;
            set
            {
                if (value != _field11)
                {
                    _field11 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field12
        {
            get => _field12;
            set
            {
                if (value != _field12)
                {
                    _field12 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field13
        {
            get => _field13;
            set
            {
                if (value != _field13)
                {
                    _field13 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field14
        {
            get => _field14;
            set
            {
                if (value != _field14)
                {
                    _field14 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field15
        {
            get => _field15;
            set
            {
                if (value != _field15)
                {
                    _field15 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field16
        {
            get => _field16;
            set
            {
                if (value != _field16)
                {
                    _field16 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field17
        {
            get => _field17;
            set
            {
                if (value != _field17)
                {
                    _field17 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field18
        {
            get => _field18;
            set
            {
                if (value != _field18)
                {
                    _field18 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field19
        {
            get => _field19;
            set
            {
                if (value != _field19)
                {
                    _field19 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field20
        {
            get => _field20;
            set
            {
                if (value != _field20)
                {
                    _field20 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field21
        {
            get => _field21;
            set
            {
                if (value != _field21)
                {
                    _field21 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field22
        {
            get => _field22;
            set
            {
                if (value != _field22)
                {
                    _field22 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field23
        {
            get => _field23;
            set
            {
                if (value != _field23)
                {
                    _field23 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field24
        {
            get => _field24;
            set
            {
                if (value != _field24)
                {
                    _field24 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field25
        {
            get => _field25;
            set
            {
                if (value != _field25)
                {
                    _field25 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field26
        {
            get => _field26;
            set
            {
                if (value != _field26)
                {
                    _field26 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field27
        {
            get => _field27;
            set
            {
                if (value != _field27)
                {
                    _field27 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field28
        {
            get => _field28;
            set
            {
                if (value != _field28)
                {
                    _field28 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field29
        {
            get => _field29;
            set
            {
                if (value != _field29)
                {
                    _field29 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field30
        {
            get => _field30;
            set
            {
                if (value != _field30)
                {
                    _field30 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field31
        {
            get => _field31;
            set
            {
                if (value != _field31)
                {
                    _field31 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field32
        {
            get => _field32;
            set
            {
                if (value != _field32)
                {
                    _field32 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field33
        {
            get => _field33;
            set
            {
                if (value != _field33)
                {
                    _field33 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public UlongFlagsItem(Server.Serial serial)
        {
            Serial = serial;
        }

        public virtual void Serialize(Server.IGenericWriter writer)
        {
            writer.WriteEncodedInt(SerializationVersion);

            var saveFlags = SaveFlag.None;
            if (ShouldSerializeField0())
            {
                saveFlags |= SaveFlag.Field0;
            }
            if (ShouldSerializeField1())
            {
                saveFlags |= SaveFlag.Field1;
            }
            if (ShouldSerializeField2())
            {
                saveFlags |= SaveFlag.Field2;
            }
            if (ShouldSerializeField3())
            {
                saveFlags |= SaveFlag.Field3;
            }
            if (ShouldSerializeField4())
            {
                saveFlags |= SaveFlag.Field4;
            }
            if (ShouldSerializeField5())
            {
                saveFlags |= SaveFlag.Field5;
            }
            if (ShouldSerializeField6())
            {
                saveFlags |= SaveFlag.Field6;
            }
            if (ShouldSerializeField7())
            {
                saveFlags |= SaveFlag.Field7;
            }
            if (ShouldSerializeField8())
            {
                saveFlags |= SaveFlag.Field8;
            }
            if (ShouldSerializeField9())
            {
                saveFlags |= SaveFlag.Field9;
            }
            if (ShouldSerializeField10())
            {
                saveFlags |= SaveFlag.Field10;
            }
            if (ShouldSerializeField11())
            {
                saveFlags |= SaveFlag.Field11;
            }
            if (ShouldSerializeField12())
            {
                saveFlags |= SaveFlag.Field12;
            }
            if (ShouldSerializeField13())
            {
                saveFlags |= SaveFlag.Field13;
            }
            if (ShouldSerializeField14())
            {
                saveFlags |= SaveFlag.Field14;
            }
            if (ShouldSerializeField15())
            {
                saveFlags |= SaveFlag.Field15;
            }
            if (ShouldSerializeField16())
            {
                saveFlags |= SaveFlag.Field16;
            }
            if (ShouldSerializeField17())
            {
                saveFlags |= SaveFlag.Field17;
            }
            if (ShouldSerializeField18())
            {
                saveFlags |= SaveFlag.Field18;
            }
            if (ShouldSerializeField19())
            {
                saveFlags |= SaveFlag.Field19;
            }
            if (ShouldSerializeField20())
            {
                saveFlags |= SaveFlag.Field20;
            }
            if (ShouldSerializeField21())
            {
                saveFlags |= SaveFlag.Field21;
            }
            if (ShouldSerializeField22())
            {
                saveFlags |= SaveFlag.Field22;
            }
            if (ShouldSerializeField23())
            {
                saveFlags |= SaveFlag.Field23;
            }
            if (ShouldSerializeField24())
            {
                saveFlags |= SaveFlag.Field24;
            }
            if (ShouldSerializeField25())
            {
                saveFlags |= SaveFlag.Field25;
            }
            if (ShouldSerializeField26())
            {
                saveFlags |= SaveFlag.Field26;
            }
            if (ShouldSerializeField27())
            {
                saveFlags |= SaveFlag.Field27;
            }
            if (ShouldSerializeField28())
            {
                saveFlags |= SaveFlag.Field28;
            }
            if (ShouldSerializeField29())
            {
                saveFlags |= SaveFlag.Field29;
            }
            if (ShouldSerializeField30())
            {
                saveFlags |= SaveFlag.Field30;
            }
            if (ShouldSerializeField31())
            {
                saveFlags |= SaveFlag.Field31;
            }
            if (ShouldSerializeField32())
            {
                saveFlags |= SaveFlag.Field32;
            }
            if (ShouldSerializeField33())
            {
                saveFlags |= SaveFlag.Field33;
            }
            writer.WriteEnum(saveFlags);

            if ((saveFlags & SaveFlag.Field0) != 0)
            {
                writer.Write(_field0);
            }

            if ((saveFlags & SaveFlag.Field1) != 0)
            {
                writer.Write(_field1);
            }

            if ((saveFlags & SaveFlag.Field2) != 0)
            {
                writer.Write(_field2);
            }

            if ((saveFlags & SaveFlag.Field3) != 0)
            {
                writer.Write(_field3);
            }

            if ((saveFlags & SaveFlag.Field4) != 0)
            {
                writer.Write(_field4);
            }

            if ((saveFlags & SaveFlag.Field5) != 0)
            {
                writer.Write(_field5);
            }

            if ((saveFlags & SaveFlag.Field6) != 0)
            {
                writer.Write(_field6);
            }

            if ((saveFlags & SaveFlag.Field7) != 0)
            {
                writer.Write(_field7);
            }

            if ((saveFlags & SaveFlag.Field8) != 0)
            {
                writer.Write(_field8);
            }

            if ((saveFlags & SaveFlag.Field9) != 0)
            {
                writer.Write(_field9);
            }

            if ((saveFlags & SaveFlag.Field10) != 0)
            {
                writer.Write(_field10);
            }

            if ((saveFlags & SaveFlag.Field11) != 0)
            {
                writer.Write(_field11);
            }

            if ((saveFlags & SaveFlag.Field12) != 0)
            {
                writer.Write(_field12);
            }

            if ((saveFlags & SaveFlag.Field13) != 0)
            {
                writer.Write(_field13);
            }

            if ((saveFlags & SaveFlag.Field14) != 0)
            {
                writer.Write(_field14);
            }

            if ((saveFlags & SaveFlag.Field15) != 0)
            {
                writer.Write(_field15);
            }

            if ((saveFlags & SaveFlag.Field16) != 0)
            {
                writer.Write(_field16);
            }

            if ((saveFlags & SaveFlag.Field17) != 0)
            {
                writer.Write(_field17);
            }

            if ((saveFlags & SaveFlag.Field18) != 0)
            {
                writer.Write(_field18);
            }

            if ((saveFlags & SaveFlag.Field19) != 0)
            {
                writer.Write(_field19);
            }

            if ((saveFlags & SaveFlag.Field20) != 0)
            {
                writer.Write(_field20);
            }

            if ((saveFlags & SaveFlag.Field21) != 0)
            {
                writer.Write(_field21);
            }

            if ((saveFlags & SaveFlag.Field22) != 0)
            {
                writer.Write(_field22);
            }

            if ((saveFlags & SaveFlag.Field23) != 0)
            {
                writer.Write(_field23);
            }

            if ((saveFlags & SaveFlag.Field24) != 0)
            {
                writer.Write(_field24);
            }

            if ((saveFlags & SaveFlag.Field25) != 0)
            {
                writer.Write(_field25);
            }

            if ((saveFlags & SaveFlag.Field26) != 0)
            {
                writer.Write(_field26);
            }

            if ((saveFlags & SaveFlag.Field27) != 0)
            {
                writer.Write(_field27);
            }

            if ((saveFlags & SaveFlag.Field28) != 0)
            {
                writer.Write(_field28);
            }

            if ((saveFlags & SaveFlag.Field29) != 0)
            {
                writer.Write(_field29);
            }

            if ((saveFlags & SaveFlag.Field30) != 0)
            {
                writer.Write(_field30);
            }

            if ((saveFlags & SaveFlag.Field31) != 0)
            {
                writer.Write(_field31);
            }

            if ((saveFlags & SaveFlag.Field32) != 0)
            {
                writer.Write(_field32);
            }

            if ((saveFlags & SaveFlag.Field33) != 0)
            {
                writer.Write(_field33);
            }
        }

        public virtual void Deserialize(Server.IGenericReader reader)
        {
            var version = reader.ReadEncodedInt();

            var saveFlags = reader.ReadEnum<SaveFlag>();

            if ((saveFlags & SaveFlag.Field0) != 0)
            {
                _field0 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field1) != 0)
            {
                _field1 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field2) != 0)
            {
                _field2 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field3) != 0)
            {
                _field3 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field4) != 0)
            {
                _field4 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field5) != 0)
            {
                _field5 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field6) != 0)
            {
                _field6 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field7) != 0)
            {
                _field7 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field8) != 0)
            {
                _field8 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field9) != 0)
            {
                _field9 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field10) != 0)
            {
                _field10 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field11) != 0)
            {
                _field11 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field12) != 0)
            {
                _field12 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field13) != 0)
            {
                _field13 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field14) != 0)
            {
                _field14 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field15) != 0)
            {
                _field15 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field16) != 0)
            {
                _field16 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field17) != 0)
            {
                _field17 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field18) != 0)
            {
                _field18 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field19) != 0)
            {
                _field19 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field20) != 0)
            {
                _field20 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field21) != 0)
            {
                _field21 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field22) != 0)
            {
                _field22 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field23) != 0)
            {
                _field23 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field24) != 0)
            {
                _field24 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field25) != 0)
            {
                _field25 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field26) != 0)
            {
                _field26 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field27) != 0)
            {
                _field27 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field28) != 0)
            {
                _field28 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field29) != 0)
            {
                _field29 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field30) != 0)
            {
                _field30 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field31) != 0)
            {
                _field31 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field32) != 0)
            {
                _field32 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field33) != 0)
            {
                _field33 = reader.ReadString();
            }
        }

        [System.Flags]
        private enum SaveFlag : ulong
        {
            None = 0x0000000000000000,
            Field0 = 0x0000000000000001,
            Field1 = 0x0000000000000002,
            Field2 = 0x0000000000000004,
            Field3 = 0x0000000000000008,
            Field4 = 0x0000000000000010,
            Field5 = 0x0000000000000020,
            Field6 = 0x0000000000000040,
            Field7 = 0x0000000000000080,
            Field8 = 0x0000000000000100,
            Field9 = 0x0000000000000200,
            Field10 = 0x0000000000000400,
            Field11 = 0x0000000000000800,
            Field12 = 0x0000000000001000,
            Field13 = 0x0000000000002000,
            Field14 = 0x0000000000004000,
            Field15 = 0x0000000000008000,
            Field16 = 0x0000000000010000,
            Field17 = 0x0000000000020000,
            Field18 = 0x0000000000040000,
            Field19 = 0x0000000000080000,
            Field20 = 0x0000000000100000,
            Field21 = 0x0000000000200000,
            Field22 = 0x0000000000400000,
            Field23 = 0x0000000000800000,
            Field24 = 0x0000000001000000,
            Field25 = 0x0000000002000000,
            Field26 = 0x0000000004000000,
            Field27 = 0x0000000008000000,
            Field28 = 0x0000000010000000,
            Field29 = 0x0000000020000000,
            Field30 = 0x0000000040000000,
            Field31 = 0x0000000080000000,
            Field32 = 0x0000000100000000,
            Field33 = 0x0000000200000000,
        }
    }
}
