// <auto-generated>
//     This code was generated by the ModernUO Serialization Generator tool.
//     Version: {VERSION}
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

#pragma warning disable

namespace Server.TestContent
{
    [System.CodeDom.Compiler.GeneratedCode("ModernUO.Serialization.Generator", "{VERSION}")]
    public partial class UOTypesItem
    {
        private const int SerializationVersion = 0;

        public Server.Serial LinkedSerial
        {
            get => _linkedSerial;
            set
            {
                if (value != _linkedSerial)
                {
                    _linkedSerial = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public Server.Point2D Location2D
        {
            get => _location2D;
            set
            {
                if (value != _location2D)
                {
                    _location2D = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public Server.Point3D Location3D
        {
            get => _location3D;
            set
            {
                if (value != _location3D)
                {
                    _location3D = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public Server.Rectangle2D Bounds2D
        {
            get => _bounds2D;
            set
            {
                if (value != _bounds2D)
                {
                    _bounds2D = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public Server.Rectangle3D Bounds3D
        {
            get => _bounds3D;
            set
            {
                if (value != _bounds3D)
                {
                    _bounds3D = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public UOTypesItem(Server.Serial serial)
        {
            Serial = serial;
        }

        public virtual void Serialize(Server.IGenericWriter writer)
        {
            writer.WriteEncodedInt(SerializationVersion);

            writer.Write(_linkedSerial);

            writer.Write(_location2D);

            writer.Write(_location3D);

            writer.Write(_bounds2D);

            writer.Write(_bounds3D);
        }

        public virtual void Deserialize(Server.IGenericReader reader)
        {
            var version = reader.ReadEncodedInt();

            _linkedSerial = reader.ReadSerial();

            _location2D = reader.ReadPoint2D();

            _location3D = reader.ReadPoint3D();

            _bounds2D = reader.ReadRect2D();

            _bounds3D = reader.ReadRect3D();
        }
    }
}
