// <auto-generated>
//     This code was generated by the ModernUO Serialization Generator tool.
//     Version: {VERSION}
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

#pragma warning disable

namespace Server.TestContent
{
    [System.CodeDom.Compiler.GeneratedCode("ModernUO.Serialization.Generator", "{VERSION}")]
    public partial class TimersItem
    {
        private const int SerializationVersion = 1;

        public Server.Timer DriftTimer
        {
            get => _driftTimer;
            set
            {
                if (value != _driftTimer)
                {
                    _driftTimer = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public Server.Timer DeadlineTimer
        {
            get => _deadlineTimer;
            set
            {
                if (value != _deadlineTimer)
                {
                    _deadlineTimer = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public TimersItem(Server.Serial serial)
        {
            Serial = serial;
        }

        ref struct V0Content
        {
            internal readonly System.DateTime DriftTimerNext;
            internal readonly System.TimeSpan DriftTimerDelay;
            internal readonly System.DateTime DeadlineTimerNext;
            internal readonly System.TimeSpan DeadlineTimerDelay;
            internal V0Content(Server.IGenericReader reader, Server.TestContent.TimersItem entity)
            {
                DriftTimerNext = reader.ReadDeltaTime();
                DriftTimerDelay = DriftTimerNext == System.DateTime.MinValue ? System.TimeSpan.MinValue : DriftTimerNext - Server.Core.Now;
                DeadlineTimerNext = reader.ReadDateTime();
                DeadlineTimerDelay = DeadlineTimerNext == System.DateTime.MinValue ? System.TimeSpan.MinValue : DeadlineTimerNext - Server.Core.Now;
            }
        }

        public virtual void Serialize(Server.IGenericWriter writer)
        {
            writer.WriteEncodedInt(SerializationVersion);

            writer.WriteAnchoredTime(DriftTimer?.Next ?? System.DateTime.MinValue);

            writer.Write(DeadlineTimer?.Next ?? System.DateTime.MinValue);
        }

        public virtual void Deserialize(Server.IGenericReader reader)
        {
            var version = reader.ReadEncodedInt();

            if (version == 0)
            {
                MigrateFrom(new V0Content(reader, this));
                Server.ISerializableExtensions.MarkDirty(this);
                return;
            }

            var DriftTimerNext = reader.ReadAnchoredTime();
            var DriftTimerDelay = DriftTimerNext == System.DateTime.MinValue ? System.TimeSpan.MinValue : DriftTimerNext - Server.Core.Now;
            if (DriftTimerNext != System.DateTime.MinValue)
            {
                RestartDriftTimer(DriftTimerDelay);
            }

            var DeadlineTimerNext = reader.ReadDateTime();
            var DeadlineTimerDelay = DeadlineTimerNext == System.DateTime.MinValue ? System.TimeSpan.MinValue : DeadlineTimerNext - Server.Core.Now;
            if (DeadlineTimerNext != System.DateTime.MinValue)
            {
                RestartDeadlineTimer(DeadlineTimerDelay);
            }
        }
    }
}
