// <auto-generated>
//     This code was generated by the ModernUO Serialization Generator tool.
//     Version: {VERSION}
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

#pragma warning disable

namespace Server.TestContent
{
    [System.CodeDom.Compiler.GeneratedCode("ModernUO.Serialization.Generator", "{VERSION}")]
    public partial record struct WideRecordStruct
    {
        private const int SerializationVersion = 0;

        public int Amount
        {
            get => _amount;
            set
            {
                if (value != _amount)
                {
                    _amount = value;
                }
            }
        }

        public string Label
        {
            get => _label;
            set
            {
                if (value != _label)
                {
                    _label = value;
                }
            }
        }

        public void Serialize(Server.IGenericWriter writer)
        {
            writer.WriteEncodedInt(SerializationVersion);

            writer.Write(_amount);

            writer.Write(_label);
        }

        public void Deserialize(Server.IGenericReader reader)
        {
            var version = reader.ReadEncodedInt();

            _amount = reader.ReadInt();

            _label = reader.ReadString();
        }
    }
}
