// <auto-generated>
//     This code was generated by the ModernUO Serialization Generator tool.
//     Version: {VERSION}
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

#pragma warning disable

namespace Server.TestContent
{
    [System.CodeDom.Compiler.GeneratedCode("ModernUO.Serialization.Generator", "{VERSION}")]
    public partial class PairItem<TKey, TValue> where TKey : class where TValue : struct
    {
        private const int SerializationVersion = 0;

        public string Label
        {
            get => _label;
            set
            {
                if (value != _label)
                {
                    _label = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public PairItem(Server.Serial serial)
        {
            Serial = serial;
        }

        public virtual void Serialize(Server.IGenericWriter writer)
        {
            writer.WriteEncodedInt(SerializationVersion);

            writer.Write(_label);
        }

        public virtual void Deserialize(Server.IGenericReader reader)
        {
            var version = reader.ReadEncodedInt();

            _label = reader.ReadString();
        }
    }
}
