// <auto-generated>
//     This code was generated by the ModernUO Serialization Generator tool.
//     Version: {VERSION}
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

#pragma warning disable

namespace Server.TestContent
{
    [System.CodeDom.Compiler.GeneratedCode("ModernUO.Serialization.Generator", "{VERSION}")]
    public partial class NoDirtyTargetRecord
    {
        private const int SerializationVersion = 0;

        public string Name
        {
            get => _name;
            set
            {
                if (value != _name)
                {
                    _name = value;
                }
            }
        }

        public System.Collections.Generic.List<int> Values
        {
            get => _values;
            set
            {
                if (value != _values)
                {
                    _values = value;
                }
            }
        }

        public void AddToValues(int value)
        {
            Values.Add(value);
        }

        public void RemoveFromValues(int value)
        {
            Values.Remove(value);
        }

        public void InsertIntoValues(int index, int value)
        {
            Values.Insert(index, value);
        }

        public void RemoveFromValuesAt(int index)
        {
            Values.RemoveAt(index);
        }

        public void ClearValues()
        {
            Values.Clear();
        }

        public System.Collections.Generic.Dictionary<int, string> Lookup
        {
            get => _lookup;
            set
            {
                if (value != _lookup)
                {
                    _lookup = value;
                }
            }
        }

        public void AddToLookup(int key, string value)
        {
            Lookup.Add(key, value);
        }

        public void RemoveFromLookup(int key)
        {
            Lookup.Remove(key);
        }

        public void ReplaceInLookup(int key, string value)
        {
            Lookup[key] = value;
        }

        public void ClearLookup()
        {
            Lookup.Clear();
        }

        public virtual void Serialize(Server.IGenericWriter writer)
        {
            writer.WriteEncodedInt(SerializationVersion);

            writer.Write(_name);

            var _valuesCount = _values?.Count ?? 0;
            writer.WriteEncodedInt(_valuesCount);
            if (_valuesCount > 0)
            {
                foreach (var _valuesEntry in _values!)
                {
                    writer.Write(_valuesEntry);
                }
            }

            var _lookupCount = _lookup?.Count ?? 0;
            writer.WriteEncodedInt(_lookupCount);
            if (_lookupCount > 0)
            {
                foreach (var (_lookupKey, _lookupValue) in _lookup!)
                {
                    writer.Write(_lookupKey);
                    writer.Write(_lookupValue);
                }
            }
        }

        public virtual void Deserialize(Server.IGenericReader reader)
        {
            var version = reader.ReadEncodedInt();

            _name = reader.ReadString();

            int _valuesEntry;
            var _valuesCount = reader.ReadEncodedInt();
            _values = new System.Collections.Generic.List<int>(_valuesCount);
            for (var _valuesIndex = 0; _valuesIndex < _valuesCount; _valuesIndex++)
            {
                _valuesEntry = reader.ReadInt();
                _values.Add(_valuesEntry);
            }

            int _lookupKey;
            string _lookupValue;
            var _lookupCount = reader.ReadEncodedInt();
            _lookup = new System.Collections.Generic.Dictionary<int, string>(_lookupCount);
            for (var _lookupIndex = 0; _lookupIndex < _lookupCount; _lookupIndex++)
            {
                _lookupKey = reader.ReadInt();
                _lookupValue = reader.ReadString();
                if (typeof(int).IsValueType || _lookupKey != default)
                {
                    _lookup.Add(_lookupKey, _lookupValue);
                }
            }
        }
    }
}
