// <auto-generated>
//     This code was generated by the ModernUO Serialization Generator tool.
//     Version: {VERSION}
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

#pragma warning disable

namespace Server.TestContent
{
    [System.CodeDom.Compiler.GeneratedCode("ModernUO.Serialization.Generator", "{VERSION}")]
    public partial class EnumsItem
    {
        private const int SerializationVersion = 0;

        public Server.TestContent.ItemQuality Quality
        {
            get => _quality;
            set
            {
                if (value != _quality)
                {
                    _quality = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public Server.TestContent.ItemTraits Traits
        {
            get => _traits;
            set
            {
                if (value != _traits)
                {
                    _traits = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public EnumsItem(Server.Serial serial)
        {
            Serial = serial;
        }

        public virtual void Serialize(Server.IGenericWriter writer)
        {
            writer.WriteEncodedInt(SerializationVersion);

            writer.WriteEnum<Server.TestContent.ItemQuality>(_quality);

            writer.WriteEnum<Server.TestContent.ItemTraits>(_traits);
        }

        public virtual void Deserialize(Server.IGenericReader reader)
        {
            var version = reader.ReadEncodedInt();

            _quality = reader.ReadEnum<Server.TestContent.ItemQuality>();

            _traits = reader.ReadEnum<Server.TestContent.ItemTraits>();
        }
    }
}
