// <auto-generated>
//     This code was generated by the ModernUO Serialization Generator tool.
//     Version: {VERSION}
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

#pragma warning disable

namespace Server.TestContent
{
    [System.CodeDom.Compiler.GeneratedCode("ModernUO.Serialization.Generator", "{VERSION}")]
    public partial class SortedSetItem
    {
        private const int SerializationVersion = 0;

        public System.Collections.Generic.SortedSet<string> Names
        {
            get => _names;
            set
            {
                if (value != _names)
                {
                    _names = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public void AddToNames(string value)
        {
            Names.Add(value);
            Server.ISerializableExtensions.MarkDirty(this);
        }

        public void RemoveFromNames(string value)
        {
            Names.Remove(value);
            Server.ISerializableExtensions.MarkDirty(this);
        }


        public void ClearNames()
        {
            Names.Clear();
            Server.ISerializableExtensions.MarkDirty(this);
        }

        public SortedSetItem(Server.Serial serial)
        {
            Serial = serial;
        }

        public virtual void Serialize(Server.IGenericWriter writer)
        {
            writer.WriteEncodedInt(SerializationVersion);

            var _namesCount = _names?.Count ?? 0;
            writer.WriteEncodedInt(_namesCount);
            if (_namesCount > 0)
            {
                foreach (var _namesEntry in _names!)
                {
                    writer.Write(_namesEntry);
                }
            }
        }

        public virtual void Deserialize(Server.IGenericReader reader)
        {
            var version = reader.ReadEncodedInt();

            string _namesEntry;
            var _namesCount = reader.ReadEncodedInt();
            _names = new System.Collections.Generic.SortedSet<string>(new Server.TestContent.CaseInsensitiveComparer());
            for (var _namesIndex = 0; _namesIndex < _namesCount; _namesIndex++)
            {
                _namesEntry = reader.ReadString();
                if (typeof(string).IsValueType || _namesEntry != default)
                {
                    _names.Add(_namesEntry);
                }
            }
        }
    }
}
