// <auto-generated>
//     This code was generated by the ModernUO Serialization Generator tool.
//     Version: {VERSION}
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

#pragma warning disable

namespace Server.TestContent
{
    [System.CodeDom.Compiler.GeneratedCode("ModernUO.Serialization.Generator", "{VERSION}")]
    public partial class WideMigratingItem
    {
        private const int SerializationVersion = 1;

        public string Name
        {
            get => _name;
            set
            {
                if (value != _name)
                {
                    _name = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public int Total
        {
            get => _total;
            set
            {
                if (value != _total)
                {
                    _total = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public WideMigratingItem(Server.Serial serial)
        {
            Serial = serial;
        }

        ref struct V0Content
        {
            internal readonly string Name;
            internal readonly int? Field0;
            internal readonly int? Field1;
            internal readonly int? Field2;
            internal readonly int? Field3;
            internal readonly int? Field4;
            internal readonly int? Field5;
            internal readonly int? Field6;
            internal readonly int? Field7;
            internal readonly int? Field8;
            internal readonly int? Field9;
            internal readonly int? Field10;
            internal readonly int? Field11;
            internal readonly int? Field12;
            internal readonly int? Field13;
            internal readonly int? Field14;
            internal readonly int? Field15;
            internal readonly int? Field16;
            internal readonly int? Field17;
            internal readonly int? Field18;
            internal readonly int? Field19;
            internal readonly int? Field20;
            internal readonly int? Field21;
            internal readonly int? Field22;
            internal readonly int? Field23;
            internal readonly int? Field24;
            internal readonly int? Field25;
            internal readonly int? Field26;
            internal readonly int? Field27;
            internal readonly int? Field28;
            internal readonly int? Field29;
            internal readonly int? Field30;
            internal readonly int? Field31;
            internal readonly int? Field32;
            internal readonly int? Field33;
            internal readonly int? Field34;
            internal readonly int? Field35;
            internal readonly int? Field36;
            internal readonly int? Field37;
            internal readonly int? Field38;
            internal readonly int? Field39;
            internal readonly int? Field40;
            internal readonly int? Field41;
            internal readonly int? Field42;
            internal readonly int? Field43;
            internal readonly int? Field44;
            internal readonly int? Field45;
            internal readonly int? Field46;
            internal readonly int? Field47;
            internal readonly int? Field48;
            internal readonly int? Field49;
            internal readonly int? Field50;
            internal readonly int? Field51;
            internal readonly int? Field52;
            internal readonly int? Field53;
            internal readonly int? Field54;
            internal readonly int? Field55;
            internal readonly int? Field56;
            internal readonly int? Field57;
            internal readonly int? Field58;
            internal readonly int? Field59;
            internal readonly int? Field60;
            internal readonly int? Field61;
            internal readonly int? Field62;
            internal readonly int? Field63;
            internal readonly int? Field64;
            internal readonly int? Field65;

            [System.Flags]
            private enum V0SaveFlag : ulong
            {
                None = 0x0000000000000000,
                Field0 = 0x0000000000000001,
                Field1 = 0x0000000000000002,
                Field2 = 0x0000000000000004,
                Field3 = 0x0000000000000008,
                Field4 = 0x0000000000000010,
                Field5 = 0x0000000000000020,
                Field6 = 0x0000000000000040,
                Field7 = 0x0000000000000080,
                Field8 = 0x0000000000000100,
                Field9 = 0x0000000000000200,
                Field10 = 0x0000000000000400,
                Field11 = 0x0000000000000800,
                Field12 = 0x0000000000001000,
                Field13 = 0x0000000000002000,
                Field14 = 0x0000000000004000,
                Field15 = 0x0000000000008000,
                Field16 = 0x0000000000010000,
                Field17 = 0x0000000000020000,
                Field18 = 0x0000000000040000,
                Field19 = 0x0000000000080000,
                Field20 = 0x0000000000100000,
                Field21 = 0x0000000000200000,
                Field22 = 0x0000000000400000,
                Field23 = 0x0000000000800000,
                Field24 = 0x0000000001000000,
                Field25 = 0x0000000002000000,
                Field26 = 0x0000000004000000,
                Field27 = 0x0000000008000000,
                Field28 = 0x0000000010000000,
                Field29 = 0x0000000020000000,
                Field30 = 0x0000000040000000,
                Field31 = 0x0000000080000000,
                Field32 = 0x0000000100000000,
                Field33 = 0x0000000200000000,
                Field34 = 0x0000000400000000,
                Field35 = 0x0000000800000000,
                Field36 = 0x0000001000000000,
                Field37 = 0x0000002000000000,
                Field38 = 0x0000004000000000,
                Field39 = 0x0000008000000000,
                Field40 = 0x0000010000000000,
                Field41 = 0x0000020000000000,
                Field42 = 0x0000040000000000,
                Field43 = 0x0000080000000000,
                Field44 = 0x0000100000000000,
                Field45 = 0x0000200000000000,
                Field46 = 0x0000400000000000,
                Field47 = 0x0000800000000000,
                Field48 = 0x0001000000000000,
                Field49 = 0x0002000000000000,
                Field50 = 0x0004000000000000,
                Field51 = 0x0008000000000000,
                Field52 = 0x0010000000000000,
                Field53 = 0x0020000000000000,
                Field54 = 0x0040000000000000,
                Field55 = 0x0080000000000000,
                Field56 = 0x0100000000000000,
                Field57 = 0x0200000000000000,
                Field58 = 0x0400000000000000,
                Field59 = 0x0800000000000000,
                Field60 = 0x1000000000000000,
                Field61 = 0x2000000000000000,
                Field62 = 0x4000000000000000,
                Field63 = 0x8000000000000000,
            }

            [System.Flags]
            private enum V0SaveFlag2 : ulong
            {
                None = 0x0000000000000000,
                Field64 = 0x0000000000000001,
                Field65 = 0x0000000000000002,
            }
            internal V0Content(Server.IGenericReader reader, Server.TestContent.WideMigratingItem entity)
            {
                var saveFlags = reader.ReadEnum<V0SaveFlag>();
                var saveFlags2 = reader.ReadEnum<V0SaveFlag2>();
                Name = reader.ReadString();

                if ((saveFlags & V0SaveFlag.Field0) != 0)
                {
                    Field0 = reader.ReadInt();
                }
                else
                {
                    Field0 = default;
                }

                if ((saveFlags & V0SaveFlag.Field1) != 0)
                {
                    Field1 = reader.ReadInt();
                }
                else
                {
                    Field1 = default;
                }

                if ((saveFlags & V0SaveFlag.Field2) != 0)
                {
                    Field2 = reader.ReadInt();
                }
                else
                {
                    Field2 = default;
                }

                if ((saveFlags & V0SaveFlag.Field3) != 0)
                {
                    Field3 = reader.ReadInt();
                }
                else
                {
                    Field3 = default;
                }

                if ((saveFlags & V0SaveFlag.Field4) != 0)
                {
                    Field4 = reader.ReadInt();
                }
                else
                {
                    Field4 = default;
                }

                if ((saveFlags & V0SaveFlag.Field5) != 0)
                {
                    Field5 = reader.ReadInt();
                }
                else
                {
                    Field5 = default;
                }

                if ((saveFlags & V0SaveFlag.Field6) != 0)
                {
                    Field6 = reader.ReadInt();
                }
                else
                {
                    Field6 = default;
                }

                if ((saveFlags & V0SaveFlag.Field7) != 0)
                {
                    Field7 = reader.ReadInt();
                }
                else
                {
                    Field7 = default;
                }

                if ((saveFlags & V0SaveFlag.Field8) != 0)
                {
                    Field8 = reader.ReadInt();
                }
                else
                {
                    Field8 = default;
                }

                if ((saveFlags & V0SaveFlag.Field9) != 0)
                {
                    Field9 = reader.ReadInt();
                }
                else
                {
                    Field9 = default;
                }

                if ((saveFlags & V0SaveFlag.Field10) != 0)
                {
                    Field10 = reader.ReadInt();
                }
                else
                {
                    Field10 = default;
                }

                if ((saveFlags & V0SaveFlag.Field11) != 0)
                {
                    Field11 = reader.ReadInt();
                }
                else
                {
                    Field11 = default;
                }

                if ((saveFlags & V0SaveFlag.Field12) != 0)
                {
                    Field12 = reader.ReadInt();
                }
                else
                {
                    Field12 = default;
                }

                if ((saveFlags & V0SaveFlag.Field13) != 0)
                {
                    Field13 = reader.ReadInt();
                }
                else
                {
                    Field13 = default;
                }

                if ((saveFlags & V0SaveFlag.Field14) != 0)
                {
                    Field14 = reader.ReadInt();
                }
                else
                {
                    Field14 = default;
                }

                if ((saveFlags & V0SaveFlag.Field15) != 0)
                {
                    Field15 = reader.ReadInt();
                }
                else
                {
                    Field15 = default;
                }

                if ((saveFlags & V0SaveFlag.Field16) != 0)
                {
                    Field16 = reader.ReadInt();
                }
                else
                {
                    Field16 = default;
                }

                if ((saveFlags & V0SaveFlag.Field17) != 0)
                {
                    Field17 = reader.ReadInt();
                }
                else
                {
                    Field17 = default;
                }

                if ((saveFlags & V0SaveFlag.Field18) != 0)
                {
                    Field18 = reader.ReadInt();
                }
                else
                {
                    Field18 = default;
                }

                if ((saveFlags & V0SaveFlag.Field19) != 0)
                {
                    Field19 = reader.ReadInt();
                }
                else
                {
                    Field19 = default;
                }

                if ((saveFlags & V0SaveFlag.Field20) != 0)
                {
                    Field20 = reader.ReadInt();
                }
                else
                {
                    Field20 = default;
                }

                if ((saveFlags & V0SaveFlag.Field21) != 0)
                {
                    Field21 = reader.ReadInt();
                }
                else
                {
                    Field21 = default;
                }

                if ((saveFlags & V0SaveFlag.Field22) != 0)
                {
                    Field22 = reader.ReadInt();
                }
                else
                {
                    Field22 = default;
                }

                if ((saveFlags & V0SaveFlag.Field23) != 0)
                {
                    Field23 = reader.ReadInt();
                }
                else
                {
                    Field23 = default;
                }

                if ((saveFlags & V0SaveFlag.Field24) != 0)
                {
                    Field24 = reader.ReadInt();
                }
                else
                {
                    Field24 = default;
                }

                if ((saveFlags & V0SaveFlag.Field25) != 0)
                {
                    Field25 = reader.ReadInt();
                }
                else
                {
                    Field25 = default;
                }

                if ((saveFlags & V0SaveFlag.Field26) != 0)
                {
                    Field26 = reader.ReadInt();
                }
                else
                {
                    Field26 = default;
                }

                if ((saveFlags & V0SaveFlag.Field27) != 0)
                {
                    Field27 = reader.ReadInt();
                }
                else
                {
                    Field27 = default;
                }

                if ((saveFlags & V0SaveFlag.Field28) != 0)
                {
                    Field28 = reader.ReadInt();
                }
                else
                {
                    Field28 = default;
                }

                if ((saveFlags & V0SaveFlag.Field29) != 0)
                {
                    Field29 = reader.ReadInt();
                }
                else
                {
                    Field29 = default;
                }

                if ((saveFlags & V0SaveFlag.Field30) != 0)
                {
                    Field30 = reader.ReadInt();
                }
                else
                {
                    Field30 = default;
                }

                if ((saveFlags & V0SaveFlag.Field31) != 0)
                {
                    Field31 = reader.ReadInt();
                }
                else
                {
                    Field31 = default;
                }

                if ((saveFlags & V0SaveFlag.Field32) != 0)
                {
                    Field32 = reader.ReadInt();
                }
                else
                {
                    Field32 = default;
                }

                if ((saveFlags & V0SaveFlag.Field33) != 0)
                {
                    Field33 = reader.ReadInt();
                }
                else
                {
                    Field33 = default;
                }

                if ((saveFlags & V0SaveFlag.Field34) != 0)
                {
                    Field34 = reader.ReadInt();
                }
                else
                {
                    Field34 = default;
                }

                if ((saveFlags & V0SaveFlag.Field35) != 0)
                {
                    Field35 = reader.ReadInt();
                }
                else
                {
                    Field35 = default;
                }

                if ((saveFlags & V0SaveFlag.Field36) != 0)
                {
                    Field36 = reader.ReadInt();
                }
                else
                {
                    Field36 = default;
                }

                if ((saveFlags & V0SaveFlag.Field37) != 0)
                {
                    Field37 = reader.ReadInt();
                }
                else
                {
                    Field37 = default;
                }

                if ((saveFlags & V0SaveFlag.Field38) != 0)
                {
                    Field38 = reader.ReadInt();
                }
                else
                {
                    Field38 = default;
                }

                if ((saveFlags & V0SaveFlag.Field39) != 0)
                {
                    Field39 = reader.ReadInt();
                }
                else
                {
                    Field39 = default;
                }

                if ((saveFlags & V0SaveFlag.Field40) != 0)
                {
                    Field40 = reader.ReadInt();
                }
                else
                {
                    Field40 = default;
                }

                if ((saveFlags & V0SaveFlag.Field41) != 0)
                {
                    Field41 = reader.ReadInt();
                }
                else
                {
                    Field41 = default;
                }

                if ((saveFlags & V0SaveFlag.Field42) != 0)
                {
                    Field42 = reader.ReadInt();
                }
                else
                {
                    Field42 = default;
                }

                if ((saveFlags & V0SaveFlag.Field43) != 0)
                {
                    Field43 = reader.ReadInt();
                }
                else
                {
                    Field43 = default;
                }

                if ((saveFlags & V0SaveFlag.Field44) != 0)
                {
                    Field44 = reader.ReadInt();
                }
                else
                {
                    Field44 = default;
                }

                if ((saveFlags & V0SaveFlag.Field45) != 0)
                {
                    Field45 = reader.ReadInt();
                }
                else
                {
                    Field45 = default;
                }

                if ((saveFlags & V0SaveFlag.Field46) != 0)
                {
                    Field46 = reader.ReadInt();
                }
                else
                {
                    Field46 = default;
                }

                if ((saveFlags & V0SaveFlag.Field47) != 0)
                {
                    Field47 = reader.ReadInt();
                }
                else
                {
                    Field47 = default;
                }

                if ((saveFlags & V0SaveFlag.Field48) != 0)
                {
                    Field48 = reader.ReadInt();
                }
                else
                {
                    Field48 = default;
                }

                if ((saveFlags & V0SaveFlag.Field49) != 0)
                {
                    Field49 = reader.ReadInt();
                }
                else
                {
                    Field49 = default;
                }

                if ((saveFlags & V0SaveFlag.Field50) != 0)
                {
                    Field50 = reader.ReadInt();
                }
                else
                {
                    Field50 = default;
                }

                if ((saveFlags & V0SaveFlag.Field51) != 0)
                {
                    Field51 = reader.ReadInt();
                }
                else
                {
                    Field51 = default;
                }

                if ((saveFlags & V0SaveFlag.Field52) != 0)
                {
                    Field52 = reader.ReadInt();
                }
                else
                {
                    Field52 = default;
                }

                if ((saveFlags & V0SaveFlag.Field53) != 0)
                {
                    Field53 = reader.ReadInt();
                }
                else
                {
                    Field53 = default;
                }

                if ((saveFlags & V0SaveFlag.Field54) != 0)
                {
                    Field54 = reader.ReadInt();
                }
                else
                {
                    Field54 = default;
                }

                if ((saveFlags & V0SaveFlag.Field55) != 0)
                {
                    Field55 = reader.ReadInt();
                }
                else
                {
                    Field55 = default;
                }

                if ((saveFlags & V0SaveFlag.Field56) != 0)
                {
                    Field56 = reader.ReadInt();
                }
                else
                {
                    Field56 = default;
                }

                if ((saveFlags & V0SaveFlag.Field57) != 0)
                {
                    Field57 = reader.ReadInt();
                }
                else
                {
                    Field57 = default;
                }

                if ((saveFlags & V0SaveFlag.Field58) != 0)
                {
                    Field58 = reader.ReadInt();
                }
                else
                {
                    Field58 = default;
                }

                if ((saveFlags & V0SaveFlag.Field59) != 0)
                {
                    Field59 = reader.ReadInt();
                }
                else
                {
                    Field59 = default;
                }

                if ((saveFlags & V0SaveFlag.Field60) != 0)
                {
                    Field60 = reader.ReadInt();
                }
                else
                {
                    Field60 = default;
                }

                if ((saveFlags & V0SaveFlag.Field61) != 0)
                {
                    Field61 = reader.ReadInt();
                }
                else
                {
                    Field61 = default;
                }

                if ((saveFlags & V0SaveFlag.Field62) != 0)
                {
                    Field62 = reader.ReadInt();
                }
                else
                {
                    Field62 = default;
                }

                if ((saveFlags & V0SaveFlag.Field63) != 0)
                {
                    Field63 = reader.ReadInt();
                }
                else
                {
                    Field63 = default;
                }

                if ((saveFlags2 & V0SaveFlag2.Field64) != 0)
                {
                    Field64 = reader.ReadInt();
                }
                else
                {
                    Field64 = default;
                }

                if ((saveFlags2 & V0SaveFlag2.Field65) != 0)
                {
                    Field65 = reader.ReadInt();
                }
                else
                {
                    Field65 = default;
                }
            }
        }

        public virtual void Serialize(Server.IGenericWriter writer)
        {
            writer.WriteEncodedInt(SerializationVersion);

            writer.Write(_name);

            writer.Write(_total);
        }

        public virtual void Deserialize(Server.IGenericReader reader)
        {
            var version = reader.ReadEncodedInt();

            if (version == 0)
            {
                MigrateFrom(new V0Content(reader, this));
                Server.ISerializableExtensions.MarkDirty(this);
                return;
            }

            _name = reader.ReadString();

            _total = reader.ReadInt();
        }
    }
}
