// <auto-generated>
//     This code was generated by the ModernUO Serialization Generator tool.
//     Version: {VERSION}
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

#pragma warning disable

namespace Server.TestContent
{
    [System.CodeDom.Compiler.GeneratedCode("ModernUO.Serialization.Generator", "{VERSION}")]
    public partial class MigratingItem
    {
        private const int SerializationVersion = 2;

        public string Name
        {
            get => _name;
            set
            {
                if (value != _name)
                {
                    _name = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public int Charges
        {
            get => _charges;
            set
            {
                if (value != _charges)
                {
                    _charges = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public bool Identified
        {
            get => _identified;
            set
            {
                if (value != _identified)
                {
                    _identified = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public MigratingItem(Server.Serial serial)
        {
            Serial = serial;
        }

        ref struct V0Content
        {
            internal readonly string Name;
            internal V0Content(IGenericReader reader, Server.TestContent.MigratingItem entity)
            {
                Name = reader.ReadString();
            }
        }

        ref struct V1Content
        {
            internal readonly string Name;
            internal readonly int Charges;
            internal V1Content(IGenericReader reader, Server.TestContent.MigratingItem entity)
            {
                Name = reader.ReadString();
                Charges = reader.ReadInt();
            }
        }

        public virtual void Serialize(Server.IGenericWriter writer)
        {
            writer.WriteEncodedInt(SerializationVersion);

            writer.Write(_name);

            writer.Write(_charges);

            writer.Write(_identified);
        }

        public virtual void Deserialize(Server.IGenericReader reader)
        {
            var version = reader.ReadEncodedInt();

            if (version == 0)
            {
                MigrateFrom(new V0Content(reader, this));
                Server.ISerializableExtensions.MarkDirty(this);
                return;
            }

            if (version == 1)
            {
                MigrateFrom(new V1Content(reader, this));
                Server.ISerializableExtensions.MarkDirty(this);
                return;
            }

            _name = reader.ReadString();

            _charges = reader.ReadInt();

            _identified = reader.ReadBool();
        }
    }
}
