// <auto-generated>
//     This code was generated by the ModernUO Serialization Generator tool.
//     Version: {VERSION}
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

#pragma warning disable

namespace Server.TestContent
{
    [System.CodeDom.Compiler.GeneratedCode("ModernUO.Serialization.Generator", "{VERSION}")]
    public partial class MultiEnumFlagsItem
    {
        private const int SerializationVersion = 0;

        public string Field0
        {
            get => _field0;
            set
            {
                if (value != _field0)
                {
                    _field0 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field1
        {
            get => _field1;
            set
            {
                if (value != _field1)
                {
                    _field1 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field2
        {
            get => _field2;
            set
            {
                if (value != _field2)
                {
                    _field2 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field3
        {
            get => _field3;
            set
            {
                if (value != _field3)
                {
                    _field3 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field4
        {
            get => _field4;
            set
            {
                if (value != _field4)
                {
                    _field4 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field5
        {
            get => _field5;
            set
            {
                if (value != _field5)
                {
                    _field5 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field6
        {
            get => _field6;
            set
            {
                if (value != _field6)
                {
                    _field6 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field7
        {
            get => _field7;
            set
            {
                if (value != _field7)
                {
                    _field7 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field8
        {
            get => _field8;
            set
            {
                if (value != _field8)
                {
                    _field8 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field9
        {
            get => _field9;
            set
            {
                if (value != _field9)
                {
                    _field9 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field10
        {
            get => _field10;
            set
            {
                if (value != _field10)
                {
                    _field10 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field11
        {
            get => _field11;
            set
            {
                if (value != _field11)
                {
                    _field11 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field12
        {
            get => _field12;
            set
            {
                if (value != _field12)
                {
                    _field12 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field13
        {
            get => _field13;
            set
            {
                if (value != _field13)
                {
                    _field13 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field14
        {
            get => _field14;
            set
            {
                if (value != _field14)
                {
                    _field14 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field15
        {
            get => _field15;
            set
            {
                if (value != _field15)
                {
                    _field15 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field16
        {
            get => _field16;
            set
            {
                if (value != _field16)
                {
                    _field16 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field17
        {
            get => _field17;
            set
            {
                if (value != _field17)
                {
                    _field17 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field18
        {
            get => _field18;
            set
            {
                if (value != _field18)
                {
                    _field18 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field19
        {
            get => _field19;
            set
            {
                if (value != _field19)
                {
                    _field19 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field20
        {
            get => _field20;
            set
            {
                if (value != _field20)
                {
                    _field20 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field21
        {
            get => _field21;
            set
            {
                if (value != _field21)
                {
                    _field21 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field22
        {
            get => _field22;
            set
            {
                if (value != _field22)
                {
                    _field22 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field23
        {
            get => _field23;
            set
            {
                if (value != _field23)
                {
                    _field23 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field24
        {
            get => _field24;
            set
            {
                if (value != _field24)
                {
                    _field24 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field25
        {
            get => _field25;
            set
            {
                if (value != _field25)
                {
                    _field25 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field26
        {
            get => _field26;
            set
            {
                if (value != _field26)
                {
                    _field26 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field27
        {
            get => _field27;
            set
            {
                if (value != _field27)
                {
                    _field27 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field28
        {
            get => _field28;
            set
            {
                if (value != _field28)
                {
                    _field28 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field29
        {
            get => _field29;
            set
            {
                if (value != _field29)
                {
                    _field29 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field30
        {
            get => _field30;
            set
            {
                if (value != _field30)
                {
                    _field30 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field31
        {
            get => _field31;
            set
            {
                if (value != _field31)
                {
                    _field31 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field32
        {
            get => _field32;
            set
            {
                if (value != _field32)
                {
                    _field32 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field33
        {
            get => _field33;
            set
            {
                if (value != _field33)
                {
                    _field33 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field34
        {
            get => _field34;
            set
            {
                if (value != _field34)
                {
                    _field34 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field35
        {
            get => _field35;
            set
            {
                if (value != _field35)
                {
                    _field35 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field36
        {
            get => _field36;
            set
            {
                if (value != _field36)
                {
                    _field36 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field37
        {
            get => _field37;
            set
            {
                if (value != _field37)
                {
                    _field37 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field38
        {
            get => _field38;
            set
            {
                if (value != _field38)
                {
                    _field38 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field39
        {
            get => _field39;
            set
            {
                if (value != _field39)
                {
                    _field39 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field40
        {
            get => _field40;
            set
            {
                if (value != _field40)
                {
                    _field40 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field41
        {
            get => _field41;
            set
            {
                if (value != _field41)
                {
                    _field41 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field42
        {
            get => _field42;
            set
            {
                if (value != _field42)
                {
                    _field42 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field43
        {
            get => _field43;
            set
            {
                if (value != _field43)
                {
                    _field43 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field44
        {
            get => _field44;
            set
            {
                if (value != _field44)
                {
                    _field44 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field45
        {
            get => _field45;
            set
            {
                if (value != _field45)
                {
                    _field45 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field46
        {
            get => _field46;
            set
            {
                if (value != _field46)
                {
                    _field46 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field47
        {
            get => _field47;
            set
            {
                if (value != _field47)
                {
                    _field47 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field48
        {
            get => _field48;
            set
            {
                if (value != _field48)
                {
                    _field48 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field49
        {
            get => _field49;
            set
            {
                if (value != _field49)
                {
                    _field49 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field50
        {
            get => _field50;
            set
            {
                if (value != _field50)
                {
                    _field50 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field51
        {
            get => _field51;
            set
            {
                if (value != _field51)
                {
                    _field51 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field52
        {
            get => _field52;
            set
            {
                if (value != _field52)
                {
                    _field52 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field53
        {
            get => _field53;
            set
            {
                if (value != _field53)
                {
                    _field53 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field54
        {
            get => _field54;
            set
            {
                if (value != _field54)
                {
                    _field54 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field55
        {
            get => _field55;
            set
            {
                if (value != _field55)
                {
                    _field55 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field56
        {
            get => _field56;
            set
            {
                if (value != _field56)
                {
                    _field56 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field57
        {
            get => _field57;
            set
            {
                if (value != _field57)
                {
                    _field57 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field58
        {
            get => _field58;
            set
            {
                if (value != _field58)
                {
                    _field58 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field59
        {
            get => _field59;
            set
            {
                if (value != _field59)
                {
                    _field59 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field60
        {
            get => _field60;
            set
            {
                if (value != _field60)
                {
                    _field60 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field61
        {
            get => _field61;
            set
            {
                if (value != _field61)
                {
                    _field61 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field62
        {
            get => _field62;
            set
            {
                if (value != _field62)
                {
                    _field62 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field63
        {
            get => _field63;
            set
            {
                if (value != _field63)
                {
                    _field63 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field64
        {
            get => _field64;
            set
            {
                if (value != _field64)
                {
                    _field64 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field65
        {
            get => _field65;
            set
            {
                if (value != _field65)
                {
                    _field65 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field66
        {
            get => _field66;
            set
            {
                if (value != _field66)
                {
                    _field66 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field67
        {
            get => _field67;
            set
            {
                if (value != _field67)
                {
                    _field67 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field68
        {
            get => _field68;
            set
            {
                if (value != _field68)
                {
                    _field68 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Field69
        {
            get => _field69;
            set
            {
                if (value != _field69)
                {
                    _field69 = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public MultiEnumFlagsItem(Server.Serial serial)
        {
            Serial = serial;
        }

        public virtual void Serialize(Server.IGenericWriter writer)
        {
            writer.WriteEncodedInt(SerializationVersion);

            var saveFlags = SaveFlag.None;

            var saveFlags2 = SaveFlag2.None;
            if (ShouldSerializeField0())
            {
                saveFlags |= SaveFlag.Field0;
            }
            if (ShouldSerializeField1())
            {
                saveFlags |= SaveFlag.Field1;
            }
            if (ShouldSerializeField2())
            {
                saveFlags |= SaveFlag.Field2;
            }
            if (ShouldSerializeField3())
            {
                saveFlags |= SaveFlag.Field3;
            }
            if (ShouldSerializeField4())
            {
                saveFlags |= SaveFlag.Field4;
            }
            if (ShouldSerializeField5())
            {
                saveFlags |= SaveFlag.Field5;
            }
            if (ShouldSerializeField6())
            {
                saveFlags |= SaveFlag.Field6;
            }
            if (ShouldSerializeField7())
            {
                saveFlags |= SaveFlag.Field7;
            }
            if (ShouldSerializeField8())
            {
                saveFlags |= SaveFlag.Field8;
            }
            if (ShouldSerializeField9())
            {
                saveFlags |= SaveFlag.Field9;
            }
            if (ShouldSerializeField10())
            {
                saveFlags |= SaveFlag.Field10;
            }
            if (ShouldSerializeField11())
            {
                saveFlags |= SaveFlag.Field11;
            }
            if (ShouldSerializeField12())
            {
                saveFlags |= SaveFlag.Field12;
            }
            if (ShouldSerializeField13())
            {
                saveFlags |= SaveFlag.Field13;
            }
            if (ShouldSerializeField14())
            {
                saveFlags |= SaveFlag.Field14;
            }
            if (ShouldSerializeField15())
            {
                saveFlags |= SaveFlag.Field15;
            }
            if (ShouldSerializeField16())
            {
                saveFlags |= SaveFlag.Field16;
            }
            if (ShouldSerializeField17())
            {
                saveFlags |= SaveFlag.Field17;
            }
            if (ShouldSerializeField18())
            {
                saveFlags |= SaveFlag.Field18;
            }
            if (ShouldSerializeField19())
            {
                saveFlags |= SaveFlag.Field19;
            }
            if (ShouldSerializeField20())
            {
                saveFlags |= SaveFlag.Field20;
            }
            if (ShouldSerializeField21())
            {
                saveFlags |= SaveFlag.Field21;
            }
            if (ShouldSerializeField22())
            {
                saveFlags |= SaveFlag.Field22;
            }
            if (ShouldSerializeField23())
            {
                saveFlags |= SaveFlag.Field23;
            }
            if (ShouldSerializeField24())
            {
                saveFlags |= SaveFlag.Field24;
            }
            if (ShouldSerializeField25())
            {
                saveFlags |= SaveFlag.Field25;
            }
            if (ShouldSerializeField26())
            {
                saveFlags |= SaveFlag.Field26;
            }
            if (ShouldSerializeField27())
            {
                saveFlags |= SaveFlag.Field27;
            }
            if (ShouldSerializeField28())
            {
                saveFlags |= SaveFlag.Field28;
            }
            if (ShouldSerializeField29())
            {
                saveFlags |= SaveFlag.Field29;
            }
            if (ShouldSerializeField30())
            {
                saveFlags |= SaveFlag.Field30;
            }
            if (ShouldSerializeField31())
            {
                saveFlags |= SaveFlag.Field31;
            }
            if (ShouldSerializeField32())
            {
                saveFlags |= SaveFlag.Field32;
            }
            if (ShouldSerializeField33())
            {
                saveFlags |= SaveFlag.Field33;
            }
            if (ShouldSerializeField34())
            {
                saveFlags |= SaveFlag.Field34;
            }
            if (ShouldSerializeField35())
            {
                saveFlags |= SaveFlag.Field35;
            }
            if (ShouldSerializeField36())
            {
                saveFlags |= SaveFlag.Field36;
            }
            if (ShouldSerializeField37())
            {
                saveFlags |= SaveFlag.Field37;
            }
            if (ShouldSerializeField38())
            {
                saveFlags |= SaveFlag.Field38;
            }
            if (ShouldSerializeField39())
            {
                saveFlags |= SaveFlag.Field39;
            }
            if (ShouldSerializeField40())
            {
                saveFlags |= SaveFlag.Field40;
            }
            if (ShouldSerializeField41())
            {
                saveFlags |= SaveFlag.Field41;
            }
            if (ShouldSerializeField42())
            {
                saveFlags |= SaveFlag.Field42;
            }
            if (ShouldSerializeField43())
            {
                saveFlags |= SaveFlag.Field43;
            }
            if (ShouldSerializeField44())
            {
                saveFlags |= SaveFlag.Field44;
            }
            if (ShouldSerializeField45())
            {
                saveFlags |= SaveFlag.Field45;
            }
            if (ShouldSerializeField46())
            {
                saveFlags |= SaveFlag.Field46;
            }
            if (ShouldSerializeField47())
            {
                saveFlags |= SaveFlag.Field47;
            }
            if (ShouldSerializeField48())
            {
                saveFlags |= SaveFlag.Field48;
            }
            if (ShouldSerializeField49())
            {
                saveFlags |= SaveFlag.Field49;
            }
            if (ShouldSerializeField50())
            {
                saveFlags |= SaveFlag.Field50;
            }
            if (ShouldSerializeField51())
            {
                saveFlags |= SaveFlag.Field51;
            }
            if (ShouldSerializeField52())
            {
                saveFlags |= SaveFlag.Field52;
            }
            if (ShouldSerializeField53())
            {
                saveFlags |= SaveFlag.Field53;
            }
            if (ShouldSerializeField54())
            {
                saveFlags |= SaveFlag.Field54;
            }
            if (ShouldSerializeField55())
            {
                saveFlags |= SaveFlag.Field55;
            }
            if (ShouldSerializeField56())
            {
                saveFlags |= SaveFlag.Field56;
            }
            if (ShouldSerializeField57())
            {
                saveFlags |= SaveFlag.Field57;
            }
            if (ShouldSerializeField58())
            {
                saveFlags |= SaveFlag.Field58;
            }
            if (ShouldSerializeField59())
            {
                saveFlags |= SaveFlag.Field59;
            }
            if (ShouldSerializeField60())
            {
                saveFlags |= SaveFlag.Field60;
            }
            if (ShouldSerializeField61())
            {
                saveFlags |= SaveFlag.Field61;
            }
            if (ShouldSerializeField62())
            {
                saveFlags |= SaveFlag.Field62;
            }
            if (ShouldSerializeField63())
            {
                saveFlags |= SaveFlag.Field63;
            }
            if (ShouldSerializeField64())
            {
                saveFlags2 |= SaveFlag2.Field64;
            }
            if (ShouldSerializeField65())
            {
                saveFlags2 |= SaveFlag2.Field65;
            }
            if (ShouldSerializeField66())
            {
                saveFlags2 |= SaveFlag2.Field66;
            }
            if (ShouldSerializeField67())
            {
                saveFlags2 |= SaveFlag2.Field67;
            }
            if (ShouldSerializeField68())
            {
                saveFlags2 |= SaveFlag2.Field68;
            }
            if (ShouldSerializeField69())
            {
                saveFlags2 |= SaveFlag2.Field69;
            }
            writer.WriteEnum(saveFlags);
            writer.WriteEnum(saveFlags2);

            if ((saveFlags & SaveFlag.Field0) != 0)
            {
                writer.Write(_field0);
            }

            if ((saveFlags & SaveFlag.Field1) != 0)
            {
                writer.Write(_field1);
            }

            if ((saveFlags & SaveFlag.Field2) != 0)
            {
                writer.Write(_field2);
            }

            if ((saveFlags & SaveFlag.Field3) != 0)
            {
                writer.Write(_field3);
            }

            if ((saveFlags & SaveFlag.Field4) != 0)
            {
                writer.Write(_field4);
            }

            if ((saveFlags & SaveFlag.Field5) != 0)
            {
                writer.Write(_field5);
            }

            if ((saveFlags & SaveFlag.Field6) != 0)
            {
                writer.Write(_field6);
            }

            if ((saveFlags & SaveFlag.Field7) != 0)
            {
                writer.Write(_field7);
            }

            if ((saveFlags & SaveFlag.Field8) != 0)
            {
                writer.Write(_field8);
            }

            if ((saveFlags & SaveFlag.Field9) != 0)
            {
                writer.Write(_field9);
            }

            if ((saveFlags & SaveFlag.Field10) != 0)
            {
                writer.Write(_field10);
            }

            if ((saveFlags & SaveFlag.Field11) != 0)
            {
                writer.Write(_field11);
            }

            if ((saveFlags & SaveFlag.Field12) != 0)
            {
                writer.Write(_field12);
            }

            if ((saveFlags & SaveFlag.Field13) != 0)
            {
                writer.Write(_field13);
            }

            if ((saveFlags & SaveFlag.Field14) != 0)
            {
                writer.Write(_field14);
            }

            if ((saveFlags & SaveFlag.Field15) != 0)
            {
                writer.Write(_field15);
            }

            if ((saveFlags & SaveFlag.Field16) != 0)
            {
                writer.Write(_field16);
            }

            if ((saveFlags & SaveFlag.Field17) != 0)
            {
                writer.Write(_field17);
            }

            if ((saveFlags & SaveFlag.Field18) != 0)
            {
                writer.Write(_field18);
            }

            if ((saveFlags & SaveFlag.Field19) != 0)
            {
                writer.Write(_field19);
            }

            if ((saveFlags & SaveFlag.Field20) != 0)
            {
                writer.Write(_field20);
            }

            if ((saveFlags & SaveFlag.Field21) != 0)
            {
                writer.Write(_field21);
            }

            if ((saveFlags & SaveFlag.Field22) != 0)
            {
                writer.Write(_field22);
            }

            if ((saveFlags & SaveFlag.Field23) != 0)
            {
                writer.Write(_field23);
            }

            if ((saveFlags & SaveFlag.Field24) != 0)
            {
                writer.Write(_field24);
            }

            if ((saveFlags & SaveFlag.Field25) != 0)
            {
                writer.Write(_field25);
            }

            if ((saveFlags & SaveFlag.Field26) != 0)
            {
                writer.Write(_field26);
            }

            if ((saveFlags & SaveFlag.Field27) != 0)
            {
                writer.Write(_field27);
            }

            if ((saveFlags & SaveFlag.Field28) != 0)
            {
                writer.Write(_field28);
            }

            if ((saveFlags & SaveFlag.Field29) != 0)
            {
                writer.Write(_field29);
            }

            if ((saveFlags & SaveFlag.Field30) != 0)
            {
                writer.Write(_field30);
            }

            if ((saveFlags & SaveFlag.Field31) != 0)
            {
                writer.Write(_field31);
            }

            if ((saveFlags & SaveFlag.Field32) != 0)
            {
                writer.Write(_field32);
            }

            if ((saveFlags & SaveFlag.Field33) != 0)
            {
                writer.Write(_field33);
            }

            if ((saveFlags & SaveFlag.Field34) != 0)
            {
                writer.Write(_field34);
            }

            if ((saveFlags & SaveFlag.Field35) != 0)
            {
                writer.Write(_field35);
            }

            if ((saveFlags & SaveFlag.Field36) != 0)
            {
                writer.Write(_field36);
            }

            if ((saveFlags & SaveFlag.Field37) != 0)
            {
                writer.Write(_field37);
            }

            if ((saveFlags & SaveFlag.Field38) != 0)
            {
                writer.Write(_field38);
            }

            if ((saveFlags & SaveFlag.Field39) != 0)
            {
                writer.Write(_field39);
            }

            if ((saveFlags & SaveFlag.Field40) != 0)
            {
                writer.Write(_field40);
            }

            if ((saveFlags & SaveFlag.Field41) != 0)
            {
                writer.Write(_field41);
            }

            if ((saveFlags & SaveFlag.Field42) != 0)
            {
                writer.Write(_field42);
            }

            if ((saveFlags & SaveFlag.Field43) != 0)
            {
                writer.Write(_field43);
            }

            if ((saveFlags & SaveFlag.Field44) != 0)
            {
                writer.Write(_field44);
            }

            if ((saveFlags & SaveFlag.Field45) != 0)
            {
                writer.Write(_field45);
            }

            if ((saveFlags & SaveFlag.Field46) != 0)
            {
                writer.Write(_field46);
            }

            if ((saveFlags & SaveFlag.Field47) != 0)
            {
                writer.Write(_field47);
            }

            if ((saveFlags & SaveFlag.Field48) != 0)
            {
                writer.Write(_field48);
            }

            if ((saveFlags & SaveFlag.Field49) != 0)
            {
                writer.Write(_field49);
            }

            if ((saveFlags & SaveFlag.Field50) != 0)
            {
                writer.Write(_field50);
            }

            if ((saveFlags & SaveFlag.Field51) != 0)
            {
                writer.Write(_field51);
            }

            if ((saveFlags & SaveFlag.Field52) != 0)
            {
                writer.Write(_field52);
            }

            if ((saveFlags & SaveFlag.Field53) != 0)
            {
                writer.Write(_field53);
            }

            if ((saveFlags & SaveFlag.Field54) != 0)
            {
                writer.Write(_field54);
            }

            if ((saveFlags & SaveFlag.Field55) != 0)
            {
                writer.Write(_field55);
            }

            if ((saveFlags & SaveFlag.Field56) != 0)
            {
                writer.Write(_field56);
            }

            if ((saveFlags & SaveFlag.Field57) != 0)
            {
                writer.Write(_field57);
            }

            if ((saveFlags & SaveFlag.Field58) != 0)
            {
                writer.Write(_field58);
            }

            if ((saveFlags & SaveFlag.Field59) != 0)
            {
                writer.Write(_field59);
            }

            if ((saveFlags & SaveFlag.Field60) != 0)
            {
                writer.Write(_field60);
            }

            if ((saveFlags & SaveFlag.Field61) != 0)
            {
                writer.Write(_field61);
            }

            if ((saveFlags & SaveFlag.Field62) != 0)
            {
                writer.Write(_field62);
            }

            if ((saveFlags & SaveFlag.Field63) != 0)
            {
                writer.Write(_field63);
            }

            if ((saveFlags2 & SaveFlag2.Field64) != 0)
            {
                writer.Write(_field64);
            }

            if ((saveFlags2 & SaveFlag2.Field65) != 0)
            {
                writer.Write(_field65);
            }

            if ((saveFlags2 & SaveFlag2.Field66) != 0)
            {
                writer.Write(_field66);
            }

            if ((saveFlags2 & SaveFlag2.Field67) != 0)
            {
                writer.Write(_field67);
            }

            if ((saveFlags2 & SaveFlag2.Field68) != 0)
            {
                writer.Write(_field68);
            }

            if ((saveFlags2 & SaveFlag2.Field69) != 0)
            {
                writer.Write(_field69);
            }
        }

        public virtual void Deserialize(Server.IGenericReader reader)
        {
            var version = reader.ReadEncodedInt();

            var saveFlags = reader.ReadEnum<SaveFlag>();
            var saveFlags2 = reader.ReadEnum<SaveFlag2>();

            if ((saveFlags & SaveFlag.Field0) != 0)
            {
                _field0 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field1) != 0)
            {
                _field1 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field2) != 0)
            {
                _field2 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field3) != 0)
            {
                _field3 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field4) != 0)
            {
                _field4 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field5) != 0)
            {
                _field5 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field6) != 0)
            {
                _field6 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field7) != 0)
            {
                _field7 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field8) != 0)
            {
                _field8 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field9) != 0)
            {
                _field9 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field10) != 0)
            {
                _field10 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field11) != 0)
            {
                _field11 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field12) != 0)
            {
                _field12 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field13) != 0)
            {
                _field13 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field14) != 0)
            {
                _field14 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field15) != 0)
            {
                _field15 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field16) != 0)
            {
                _field16 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field17) != 0)
            {
                _field17 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field18) != 0)
            {
                _field18 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field19) != 0)
            {
                _field19 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field20) != 0)
            {
                _field20 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field21) != 0)
            {
                _field21 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field22) != 0)
            {
                _field22 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field23) != 0)
            {
                _field23 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field24) != 0)
            {
                _field24 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field25) != 0)
            {
                _field25 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field26) != 0)
            {
                _field26 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field27) != 0)
            {
                _field27 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field28) != 0)
            {
                _field28 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field29) != 0)
            {
                _field29 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field30) != 0)
            {
                _field30 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field31) != 0)
            {
                _field31 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field32) != 0)
            {
                _field32 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field33) != 0)
            {
                _field33 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field34) != 0)
            {
                _field34 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field35) != 0)
            {
                _field35 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field36) != 0)
            {
                _field36 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field37) != 0)
            {
                _field37 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field38) != 0)
            {
                _field38 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field39) != 0)
            {
                _field39 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field40) != 0)
            {
                _field40 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field41) != 0)
            {
                _field41 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field42) != 0)
            {
                _field42 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field43) != 0)
            {
                _field43 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field44) != 0)
            {
                _field44 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field45) != 0)
            {
                _field45 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field46) != 0)
            {
                _field46 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field47) != 0)
            {
                _field47 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field48) != 0)
            {
                _field48 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field49) != 0)
            {
                _field49 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field50) != 0)
            {
                _field50 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field51) != 0)
            {
                _field51 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field52) != 0)
            {
                _field52 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field53) != 0)
            {
                _field53 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field54) != 0)
            {
                _field54 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field55) != 0)
            {
                _field55 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field56) != 0)
            {
                _field56 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field57) != 0)
            {
                _field57 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field58) != 0)
            {
                _field58 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field59) != 0)
            {
                _field59 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field60) != 0)
            {
                _field60 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field61) != 0)
            {
                _field61 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field62) != 0)
            {
                _field62 = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Field63) != 0)
            {
                _field63 = reader.ReadString();
            }

            if ((saveFlags2 & SaveFlag2.Field64) != 0)
            {
                _field64 = reader.ReadString();
            }

            if ((saveFlags2 & SaveFlag2.Field65) != 0)
            {
                _field65 = reader.ReadString();
            }

            if ((saveFlags2 & SaveFlag2.Field66) != 0)
            {
                _field66 = reader.ReadString();
            }

            if ((saveFlags2 & SaveFlag2.Field67) != 0)
            {
                _field67 = reader.ReadString();
            }

            if ((saveFlags2 & SaveFlag2.Field68) != 0)
            {
                _field68 = reader.ReadString();
            }

            if ((saveFlags2 & SaveFlag2.Field69) != 0)
            {
                _field69 = reader.ReadString();
            }
        }

        [System.Flags]
        private enum SaveFlag : ulong
        {
            None = 0x0000000000000000,
            Field0 = 0x0000000000000001,
            Field1 = 0x0000000000000002,
            Field2 = 0x0000000000000004,
            Field3 = 0x0000000000000008,
            Field4 = 0x0000000000000010,
            Field5 = 0x0000000000000020,
            Field6 = 0x0000000000000040,
            Field7 = 0x0000000000000080,
            Field8 = 0x0000000000000100,
            Field9 = 0x0000000000000200,
            Field10 = 0x0000000000000400,
            Field11 = 0x0000000000000800,
            Field12 = 0x0000000000001000,
            Field13 = 0x0000000000002000,
            Field14 = 0x0000000000004000,
            Field15 = 0x0000000000008000,
            Field16 = 0x0000000000010000,
            Field17 = 0x0000000000020000,
            Field18 = 0x0000000000040000,
            Field19 = 0x0000000000080000,
            Field20 = 0x0000000000100000,
            Field21 = 0x0000000000200000,
            Field22 = 0x0000000000400000,
            Field23 = 0x0000000000800000,
            Field24 = 0x0000000001000000,
            Field25 = 0x0000000002000000,
            Field26 = 0x0000000004000000,
            Field27 = 0x0000000008000000,
            Field28 = 0x0000000010000000,
            Field29 = 0x0000000020000000,
            Field30 = 0x0000000040000000,
            Field31 = 0x0000000080000000,
            Field32 = 0x0000000100000000,
            Field33 = 0x0000000200000000,
            Field34 = 0x0000000400000000,
            Field35 = 0x0000000800000000,
            Field36 = 0x0000001000000000,
            Field37 = 0x0000002000000000,
            Field38 = 0x0000004000000000,
            Field39 = 0x0000008000000000,
            Field40 = 0x0000010000000000,
            Field41 = 0x0000020000000000,
            Field42 = 0x0000040000000000,
            Field43 = 0x0000080000000000,
            Field44 = 0x0000100000000000,
            Field45 = 0x0000200000000000,
            Field46 = 0x0000400000000000,
            Field47 = 0x0000800000000000,
            Field48 = 0x0001000000000000,
            Field49 = 0x0002000000000000,
            Field50 = 0x0004000000000000,
            Field51 = 0x0008000000000000,
            Field52 = 0x0010000000000000,
            Field53 = 0x0020000000000000,
            Field54 = 0x0040000000000000,
            Field55 = 0x0080000000000000,
            Field56 = 0x0100000000000000,
            Field57 = 0x0200000000000000,
            Field58 = 0x0400000000000000,
            Field59 = 0x0800000000000000,
            Field60 = 0x1000000000000000,
            Field61 = 0x2000000000000000,
            Field62 = 0x4000000000000000,
            Field63 = 0x8000000000000000,
        }

        [System.Flags]
        private enum SaveFlag2 : ulong
        {
            None = 0x0000000000000000,
            Field64 = 0x0000000000000001,
            Field65 = 0x0000000000000002,
            Field66 = 0x0000000000000004,
            Field67 = 0x0000000000000008,
            Field68 = 0x0000000000000010,
            Field69 = 0x0000000000000020,
        }
    }
}
