// <auto-generated>
//     This code was generated by the ModernUO Serialization Generator tool.
//     Version: {VERSION}
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

#pragma warning disable

namespace Server.TestContent
{
    [System.CodeDom.Compiler.GeneratedCode("ModernUO.Serialization.Generator", "{VERSION}")]
    public partial class DerivedItem
    {
        private const int SerializationVersion = 0;

        public int Bonus
        {
            get => _bonus;
            set
            {
                if (value != _bonus)
                {
                    _bonus = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public DerivedItem(Server.Serial serial) : base(serial)
        {
        }

        public override void Serialize(Server.IGenericWriter writer)
        {
            base.Serialize(writer);

            writer.WriteEncodedInt(SerializationVersion);

            writer.Write(_bonus);
        }

        public override void Deserialize(Server.IGenericReader reader)
        {
            base.Deserialize(reader);

            var version = reader.ReadEncodedInt();

            _bonus = reader.ReadInt();
        }
    }
}
