// <auto-generated>
//     This code was generated by the ModernUO Serialization Generator tool.
//     Version: {VERSION}
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

#pragma warning disable

namespace Server.TestContent
{
    [System.CodeDom.Compiler.GeneratedCode("ModernUO.Serialization.Generator", "{VERSION}")]
    public partial struct Stats
    {
        private const int SerializationVersion = 0;

        public int Strength
        {
            get => _strength;
            set
            {
                if (value != _strength)
                {
                    _strength = value;
                }
            }
        }

        public void Serialize(Server.IGenericWriter writer)
        {
            writer.WriteEncodedInt(SerializationVersion);

            writer.Write(_strength);
        }

        public void Deserialize(Server.IGenericReader reader)
        {
            var version = reader.ReadEncodedInt();

            _strength = reader.ReadInt();
        }
    }
}
