// <auto-generated>
//     This code was generated by the ModernUO Serialization Generator tool.
//     Version: {VERSION}
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

#pragma warning disable

namespace Server.TestContent
{
    [System.CodeDom.Compiler.GeneratedCode("ModernUO.Serialization.Generator", "{VERSION}")]
    public partial class NullableValuesItem
    {
        private const int SerializationVersion = 1;

        public int? Count
        {
            get => _count;
            set
            {
                if (value != _count)
                {
                    _count = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public int? Encoded
        {
            get => _encoded;
            set
            {
                if (value != _encoded)
                {
                    _encoded = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public Server.TestContent.Mood? Mood
        {
            get => _mood;
            set
            {
                if (value != _mood)
                {
                    _mood = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public Server.Point3D? Location
        {
            get => _location;
            set
            {
                if (value != _location)
                {
                    _location = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public System.TimeSpan? Cooldown
        {
            get => _cooldown;
            set
            {
                if (value != _cooldown)
                {
                    _cooldown = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public Server.TestContent.Stats? Stats
        {
            get => _stats;
            set
            {
                if (!System.Collections.Generic.EqualityComparer<Server.TestContent.Stats?>.Default.Equals(value, _stats))
                {
                    _stats = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public System.Collections.Generic.List<int?> Samples
        {
            get => _samples;
            set
            {
                if (value != _samples)
                {
                    _samples = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public void AddToSamples(int? value)
        {
            _samples ??= new System.Collections.Generic.List<int?>();
            _samples.Add(value);
            Server.ISerializableExtensions.MarkDirty(this);
        }

        public void RemoveFromSamples(int? value)
        {
            if (_samples?.Remove(value) == true)
            {
                Server.ISerializableExtensions.MarkDirty(this);
            }
        }

        public void InsertIntoSamples(int index, int? value)
        {
            _samples ??= new System.Collections.Generic.List<int?>();
            _samples.Insert(index, value);
            Server.ISerializableExtensions.MarkDirty(this);
        }

        public void RemoveFromSamplesAt(int index)
        {
            if (_samples != null)
            {
                _samples.RemoveAt(index);
                Server.ISerializableExtensions.MarkDirty(this);
            }
        }

        public void ClearSamples()
        {
            if (_samples?.Count > 0)
            {
                _samples.Clear();
                Server.ISerializableExtensions.MarkDirty(this);
            }
        }

        public System.Collections.Generic.Dictionary<int, double?> Weights
        {
            get => _weights;
            set
            {
                if (value != _weights)
                {
                    _weights = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public void AddToWeights(int key, double? value)
        {
            _weights ??= new System.Collections.Generic.Dictionary<int, double?>();
            if (_weights.TryAdd(key, value))
            {
                Server.ISerializableExtensions.MarkDirty(this);
            }
        }

        public void RemoveFromWeights(int key)
        {
            if (_weights?.Remove(key) == true)
            {
                Server.ISerializableExtensions.MarkDirty(this);
            }
        }

        public void ReplaceInWeights(int key, double? value)
        {
            _weights ??= new System.Collections.Generic.Dictionary<int, double?>();
            _weights[key] = value;
            Server.ISerializableExtensions.MarkDirty(this);
        }

        public void ClearWeights()
        {
            if (_weights?.Count > 0)
            {
                _weights.Clear();
                Server.ISerializableExtensions.MarkDirty(this);
            }
        }

        public int? Bonus
        {
            get => _bonus;
            set
            {
                if (value != _bonus)
                {
                    _bonus = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public NullableValuesItem(Server.Serial serial)
        {
            Serial = serial;
        }

        ref struct V0Content
        {
            internal readonly int? Count;
            internal readonly int? Bonus;

            [System.Flags]
            private enum V0SaveFlag
            {
                None = 0x00000000,
                Bonus = 0x00000001,
            }
            internal V0Content(Server.IGenericReader reader, Server.TestContent.NullableValuesItem entity)
            {
                var saveFlags = reader.ReadEnum<V0SaveFlag>();
                if (reader.ReadBool())
                {
                    int CountValue;
                    CountValue = reader.ReadInt();
                    Count = CountValue;
                }
                else
                {
                    Count = null;
                }

                if ((saveFlags & V0SaveFlag.Bonus) != 0)
                {
                    if (reader.ReadBool())
                    {
                        int BonusValue;
                        BonusValue = reader.ReadInt();
                        Bonus = BonusValue;
                    }
                    else
                    {
                        Bonus = null;
                    }
                }
                else
                {
                    Bonus = default;
                }
            }
        }

        public virtual void Serialize(Server.IGenericWriter writer)
        {
            writer.WriteEncodedInt(SerializationVersion);

            var saveFlags = SaveFlag.None;
            if (ShouldSerializeBonus())
            {
                saveFlags |= SaveFlag.Bonus;
            }
            writer.WriteEnum(saveFlags);

            writer.Write(_count.HasValue);
            if (_count.HasValue)
            {
                var _countValue = _count.Value;
                writer.Write(_countValue);
            }

            writer.Write(_encoded.HasValue);
            if (_encoded.HasValue)
            {
                var _encodedValue = _encoded.Value;
                writer.WriteEncodedInt(_encodedValue);
            }

            writer.Write(_mood.HasValue);
            if (_mood.HasValue)
            {
                var _moodValue = _mood.Value;
                writer.WriteEnum<Server.TestContent.Mood>(_moodValue);
            }

            writer.Write(_location.HasValue);
            if (_location.HasValue)
            {
                var _locationValue = _location.Value;
                writer.Write(_locationValue);
            }

            writer.Write(_cooldown.HasValue);
            if (_cooldown.HasValue)
            {
                var _cooldownValue = _cooldown.Value;
                writer.Write(_cooldownValue);
            }

            writer.Write(_stats.HasValue);
            if (_stats.HasValue)
            {
                var _statsValue = _stats.Value;
                _statsValue.Serialize(writer);
            }

            var _samplesCount = _samples?.Count ?? 0;
            writer.WriteEncodedInt(_samplesCount);
            if (_samplesCount > 0)
            {
                foreach (var _samplesEntry in _samples!)
                {
                    writer.Write(_samplesEntry.HasValue);
                    if (_samplesEntry.HasValue)
                    {
                        var _samplesEntryValue = _samplesEntry.Value;
                        writer.Write(_samplesEntryValue);
                    }
                }
            }

            var _weightsCount = _weights?.Count ?? 0;
            writer.WriteEncodedInt(_weightsCount);
            if (_weightsCount > 0)
            {
                foreach (var (_weightsKey, _weightsValue) in _weights!)
                {
                    writer.Write(_weightsKey);
                    writer.Write(_weightsValue.HasValue);
                    if (_weightsValue.HasValue)
                    {
                        var _weightsValueValue = _weightsValue.Value;
                        writer.Write(_weightsValueValue);
                    }
                }
            }

            if ((saveFlags & SaveFlag.Bonus) != 0)
            {
                writer.Write(_bonus.HasValue);
                if (_bonus.HasValue)
                {
                    var _bonusValue = _bonus.Value;
                    writer.Write(_bonusValue);
                }
            }
        }

        public virtual void Deserialize(Server.IGenericReader reader)
        {
            var version = reader.ReadEncodedInt();

            if (version == 0)
            {
                MigrateFrom(new V0Content(reader, this));
                Server.ISerializableExtensions.MarkDirty(this);
                return;
            }

            var saveFlags = reader.ReadEnum<SaveFlag>();

            if (reader.ReadBool())
            {
                int _countValue;
                _countValue = reader.ReadInt();
                _count = _countValue;
            }
            else
            {
                _count = null;
            }

            if (reader.ReadBool())
            {
                int _encodedValue;
                _encodedValue = reader.ReadEncodedInt();
                _encoded = _encodedValue;
            }
            else
            {
                _encoded = null;
            }

            if (reader.ReadBool())
            {
                Server.TestContent.Mood _moodValue;
                _moodValue = reader.ReadEnum<Server.TestContent.Mood>();
                _mood = _moodValue;
            }
            else
            {
                _mood = null;
            }

            if (reader.ReadBool())
            {
                Server.Point3D _locationValue;
                _locationValue = reader.ReadPoint3D();
                _location = _locationValue;
            }
            else
            {
                _location = null;
            }

            if (reader.ReadBool())
            {
                System.TimeSpan _cooldownValue;
                _cooldownValue = reader.ReadTimeSpan();
                _cooldown = _cooldownValue;
            }
            else
            {
                _cooldown = null;
            }

            if (reader.ReadBool())
            {
                Server.TestContent.Stats _statsValue;
                _statsValue = new Server.TestContent.Stats();
                _statsValue.Deserialize(reader);
                _stats = _statsValue;
            }
            else
            {
                _stats = null;
            }

            int? _samplesEntry;
            var _samplesCount = reader.ReadEncodedInt();
            _samples = new System.Collections.Generic.List<int?>(_samplesCount);
            for (var _samplesIndex = 0; _samplesIndex < _samplesCount; _samplesIndex++)
            {
                if (reader.ReadBool())
                {
                    int _samplesEntryValue;
                    _samplesEntryValue = reader.ReadInt();
                    _samplesEntry = _samplesEntryValue;
                }
                else
                {
                    _samplesEntry = null;
                }
                _samples.Add(_samplesEntry);
            }

            int _weightsKey;
            double? _weightsValue;
            var _weightsCount = reader.ReadEncodedInt();
            _weights = new System.Collections.Generic.Dictionary<int, double?>(_weightsCount);
            for (var _weightsIndex = 0; _weightsIndex < _weightsCount; _weightsIndex++)
            {
                _weightsKey = reader.ReadInt();
                if (reader.ReadBool())
                {
                    double _weightsValueValue;
                    _weightsValueValue = reader.ReadDouble();
                    _weightsValue = _weightsValueValue;
                }
                else
                {
                    _weightsValue = null;
                }
                if (typeof(int).IsValueType || _weightsKey != default)
                {
                    _weights.Add(_weightsKey, _weightsValue);
                }
            }

            if ((saveFlags & SaveFlag.Bonus) != 0)
            {
                if (reader.ReadBool())
                {
                    int _bonusValue;
                    _bonusValue = reader.ReadInt();
                    _bonus = _bonusValue;
                }
                else
                {
                    _bonus = null;
                }
            }
        }

        [System.Flags]
        private enum SaveFlag
        {
            None = 0x00000000,
            Bonus = 0x00000001,
        }
    }
}
