/*************************************************************************
 * ModernUO                                                              *
 * Copyright 2019-2023 - ModernUO Development Team                       *
 * Email: hi@modernuo.com                                                *
 * File: SerializableEntityGeneration.Class.cs                           *
 *                                                                       *
 * This program is free software: you can redistribute it and/or modify  *
 * it under the terms of the GNU General Public License as published by  *
 * the Free Software Foundation, either version 3 of the License, or     *
 * (at your option) any later version.                                   *
 *                                                                       *
 * You should have received a copy of the GNU General Public License     *
 * along with this program.  If not, see <http://www.gnu.org/licenses/>. *
 *************************************************************************/

using System.Collections.Generic;
using System.Collections.Immutable;
using System.Reflection;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;

namespace ModernUO.Serialization.Generator;

public static partial class SerializableEntityGeneration
{
    public static readonly string Version = Assembly.GetExecutingAssembly().GetName().Version.ToString();

    /// <summary>
    /// Emits the serialization partial class from a fully resolved model. Symbol-free by
    /// design: everything here must come from the model so the output stage can be cached.
    /// </summary>
    public static (string Source, SerializableMetadata Migration) GenerateFromModel(
        SerializationModel model,
        ImmutableArray<SerializableMetadata> migrations,
        bool generateMetadata,
        CancellationToken token
    )
    {
        token.ThrowIfCancellationRequested();

        var source = new StringBuilder();

        source.AppendLine($"""
                           // <auto-generated>
                           //     This code was generated by the ModernUO Serialization Generator tool.
                           //     Version: {Version}
                           //
                           //     Changes to this file may cause incorrect behavior and will be lost if
                           //     the code is regenerated.
                           // </auto-generated>

                           """);

        source.AppendLine("#pragma warning disable\n");
        source.GenerateNamespaceStart(model.NamespaceName);

        var indent = "    ";

        // Class declarations, outermost first; only the innermost gets the attribute and keyword.
        for (var i = 0; i < model.TypeShells.Length; i++)
        {
            var shell = model.TypeShells[i];
            var last = i == model.TypeShells.Length - 1;

            if (last)
            {
                source.AppendLine($"{indent}[System.CodeDom.Compiler.GeneratedCode(\"ModernUO.Serialization.Generator\", \"{Version}\")]");
            }

            var currentTypeKeyword = last ? model.TypeKeyword : "class";
            source.Append($"{indent}{shell.Accessibility} partial {currentTypeKeyword} {shell.NameWithTypeParameters}");
            source.AppendLine($"{shell.WhereClauses}\n{indent}{{");
            indent += "    ";
        }

        source.GenerateField(
            indent,
            Accessibility.Private,
            InstanceModifier.Const,
            "int",
            "SerializationVersion",
            model.Version.ToString()
        );
        source.AppendLine();

        if (model.EmitMarkDirtyMethod)
        {
            source.GenerateMethodStart(
                indent,
                "MarkDirty",
                Accessibility.Public,
                false,
                "void",
                ImmutableArray<(string, string)>.Empty
            );

            source.AppendLine($"{indent}    {model.MarkDirtyBody};");

            source.GenerateMethodEnd(indent);
            source.AppendLine();
        }

        foreach (var backingField in model.BackingFields)
        {
            source.GenerateField(
                indent,
                Accessibility.Private,
                InstanceModifier.None,
                backingField.TypeDisplay,
                backingField.FieldName
            );
            source.AppendLine();
        }

        foreach (var field in model.FieldEmissions)
        {
            token.ThrowIfCancellationRequested();

            foreach (var attributeLine in field.AttributeLines)
            {
                source.AppendLine($"{indent}{attributeLine}");
            }

            source.GenerateSerializableProperty(indent, field, model.MarkDirtyMethod);
            source.AppendLine();

            // Skip data structure methods for readonly fields (they cannot be modified)
            var generatedDataStructureMethods = false;
            if (!field.IsReadOnly)
            {
                var propertyAccessor = field.Setter > field.Getter ? field.Setter.Value : field.Getter;
                generatedDataStructureMethods = source.GenerateDataStructureMethods(
                    indent,
                    field,
                    propertyAccessor.ToFriendlyString(),
                    model.MarkDirtyMethod
                );
            }

            if (generatedDataStructureMethods)
            {
                source.AppendLine();
            }
        }

        var serializableFields = model.Fields.AsImmutableArray();

        // Skip serial constructor for value types - they use the generated instance Deserialize
        if (!model.IsValueType && model.IsSerializable && !model.HasSerialCtor)
        {
            // Serial constructor
            source.GenerateSerialCtor(model.ClassName, indent, model.IsOverride);
            source.AppendLine();
        }

        foreach (var migration in migrations)
        {
            token.ThrowIfCancellationRequested();

            source.GenerateMigrationContentStruct(indent, migration, model.ClassDisplayString);
            source.AppendLine();
        }

        // Compute SaveFlag configuration
        // Maps field order to (enumIndex, bitIndex) for fields with save flags
        var saveFlagsByOrder = new SortedDictionary<int, SaveFlagModel>();
        foreach (var saveFlag in model.SaveFlags)
        {
            saveFlagsByOrder[saveFlag.Order] = saveFlag;
        }

        var saveFlagMapping = new Dictionary<int, (int EnumIndex, int BitIndex)>();
        var saveFlagCount = 0;
        foreach (var (order, _) in saveFlagsByOrder)
        {
            if (!serializableFields[order].IsReadOnly)
            {
                saveFlagCount++;
            }
        }

        var saveFlagUseUlong = saveFlagCount > 32;
        var saveFlagEnumCount = saveFlagCount <= 64 ? 1 : (saveFlagCount + 63) / 64;
        var bitsPerEnum = saveFlagUseUlong ? 64 : 32;

        var currentBitIndex = 0;
        var currentEnumIndex = 0;
        foreach (var (order, _) in saveFlagsByOrder)
        {
            if (serializableFields[order].IsReadOnly)
            {
                continue;
            }

            if (currentBitIndex >= bitsPerEnum)
            {
                currentBitIndex = 0;
                currentEnumIndex++;
            }

            saveFlagMapping[order] = (currentEnumIndex, currentBitIndex);
            currentBitIndex++;
        }

        // Serialize Method
        source.GenerateSerializeMethod(
            indent,
            model.SerializeOverride,
            model.EncodedVersion,
            serializableFields,
            saveFlagsByOrder,
            saveFlagMapping,
            saveFlagUseUlong,
            saveFlagEnumCount,
            !model.IsValueType
        );
        source.AppendLine();

        // Deserialize Method
        source.GenerateDeserializeMethod(
            model,
            indent,
            model.SerializeOverride,
            model.Version,
            model.EncodedVersion,
            migrations,
            serializableFields,
            model.MarkDirtyMethod,
            model.ParentReference,
            saveFlagsByOrder,
            saveFlagMapping,
            saveFlagUseUlong,
            saveFlagEnumCount,
            !model.IsValueType
        );

        // Serialize SaveFlag enum class(es)
        if (saveFlagCount > 0)
        {
            // Reset for enum generation
            currentBitIndex = 0;
            currentEnumIndex = 0;
            var isFirstEnum = true;

            foreach (var (order, _) in saveFlagsByOrder)
            {
                // Skip readonly fields
                if (serializableFields[order].IsReadOnly)
                {
                    continue;
                }

                // Start a new enum if needed
                if (currentBitIndex == 0 || currentBitIndex >= bitsPerEnum)
                {
                    if (!isFirstEnum)
                    {
                        source.GenerateEnumEnd(indent);
                    }

                    // If we're starting a new enum due to overflow, increment the enum index first
                    if (currentBitIndex >= bitsPerEnum)
                    {
                        currentBitIndex = 0;
                        currentEnumIndex++;
                    }

                    source.AppendLine();
                    var enumName = currentEnumIndex == 0 ? "SaveFlag" : $"SaveFlag{currentEnumIndex + 1}";
                    source.GenerateEnumStart(
                        enumName,
                        indent,
                        true,
                        Accessibility.Private,
                        saveFlagUseUlong ? "ulong" : null
                    );

                    if (saveFlagUseUlong)
                    {
                        source.GenerateEnumValueLong($"{indent}    ", true, "None", -1);
                    }
                    else
                    {
                        source.GenerateEnumValue($"{indent}    ", true, "None", -1);
                    }

                    isFirstEnum = false;
                }

                if (saveFlagUseUlong)
                {
                    source.GenerateEnumValueLong($"{indent}    ", true, serializableFields[order].Name, currentBitIndex++);
                }
                else
                {
                    source.GenerateEnumValue($"{indent}    ", true, serializableFields[order].Name, currentBitIndex++);
                }
            }

            if (!isFirstEnum)
            {
                source.GenerateEnumEnd(indent);
            }
        }

        for (var i = 0; i < model.TypeShells.Length; i++)
        {
            indent = indent.Substring(0, indent.Length - 4);
            source.GenerateClassEnd(indent);
        }

        source.GenerateNamespaceEnd();

        // Write the migration file (exclude readonly fields since they aren't serialized)
        // Use arity notation for generic types to match file naming convention
        SerializableMetadata newMigration = null;
        if (generateMetadata)
        {
            var builder = ImmutableArray.CreateBuilder<SerializableProperty>();
            foreach (var field in serializableFields)
            {
                if (!field.IsReadOnly)
                {
                    builder.Add(field);
                }
            }

            var serializableFieldsForMigration = builder.ToImmutable();
            newMigration = new SerializableMetadata
            {
                Version = model.Version,
                Type = model.ArityName,
                Properties = serializableFieldsForMigration.Length > 0 ? serializableFieldsForMigration : null
            };
        }

        return (source.ToString(), newMigration);
    }
}
