// <auto-generated>
//     This code was generated by the ModernUO Serialization Generator tool.
//     Version: {VERSION}
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

#pragma warning disable

namespace Server.TestContent
{
    [System.CodeDom.Compiler.GeneratedCode("ModernUO.Serialization.Generator", "{VERSION}")]
    public partial class BasicFieldsItem
    {
        private const int SerializationVersion = 0;

        public int IntValue
        {
            get => _intValue;
            set
            {
                if (value != _intValue)
                {
                    _intValue = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Name
        {
            get => _name;
            set
            {
                if (value != _name)
                {
                    _name = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public string Interned
        {
            get => _interned;
            set
            {
                if (value != _interned)
                {
                    _interned = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public bool Active
        {
            get => _active;
            set
            {
                if (value != _active)
                {
                    _active = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public double Weight
        {
            get => _weight;
            set
            {
                if (value != _weight)
                {
                    _weight = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public System.DateTime Crafted
        {
            get => _crafted;
            set
            {
                if (value != _crafted)
                {
                    _crafted = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public System.DateTime LastUsed
        {
            get => _lastUsed;
            set
            {
                if (value != _lastUsed)
                {
                    _lastUsed = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public System.TimeSpan Duration
        {
            get => _duration;
            set
            {
                if (value != _duration)
                {
                    _duration = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public System.Guid Identifier
        {
            get => _identifier;
            set
            {
                if (value != _identifier)
                {
                    _identifier = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public int Encoded
        {
            get => _encoded;
            set
            {
                if (value != _encoded)
                {
                    _encoded = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public decimal Price
        {
            get => _price;
            set
            {
                if (value != _price)
                {
                    _price = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public byte Small
        {
            get => _small;
            set
            {
                if (value != _small)
                {
                    _small = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public sbyte SignedSmall
        {
            get => _signedSmall;
            set
            {
                if (value != _signedSmall)
                {
                    _signedSmall = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public short ShortValue
        {
            get => _shortValue;
            set
            {
                if (value != _shortValue)
                {
                    _shortValue = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public ushort UnsignedShort
        {
            get => _unsignedShort;
            set
            {
                if (value != _unsignedShort)
                {
                    _unsignedShort = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public uint UnsignedInt
        {
            get => _unsignedInt;
            set
            {
                if (value != _unsignedInt)
                {
                    _unsignedInt = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public long LongValue
        {
            get => _longValue;
            set
            {
                if (value != _longValue)
                {
                    _longValue = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public ulong UnsignedLong
        {
            get => _unsignedLong;
            set
            {
                if (value != _unsignedLong)
                {
                    _unsignedLong = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public float FloatValue
        {
            get => _floatValue;
            set
            {
                if (value != _floatValue)
                {
                    _floatValue = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public int PrivateSet
        {
            get => _privateSet;
            private set
            {
                if (value != _privateSet)
                {
                    _privateSet = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public BasicFieldsItem(Server.Serial serial)
        {
            Serial = serial;
        }

        public virtual void Serialize(Server.IGenericWriter writer)
        {
            writer.WriteEncodedInt(SerializationVersion);

            writer.Write(_intValue);

            writer.Write(_name);

            writer.Write(_interned);

            writer.Write(_active);

            writer.Write(_weight);

            writer.Write(_crafted);

            writer.WriteDeltaTime(_lastUsed);

            writer.Write(_duration);

            writer.Write(_identifier);

            writer.WriteEncodedInt(_encoded);

            writer.Write(_price);

            writer.Write(_small);

            writer.Write(_signedSmall);

            writer.Write(_shortValue);

            writer.Write(_unsignedShort);

            writer.Write(_unsignedInt);

            writer.Write(_longValue);

            writer.Write(_unsignedLong);

            writer.Write(_floatValue);

            writer.Write(_privateSet);
        }

        public virtual void Deserialize(Server.IGenericReader reader)
        {
            var version = reader.ReadEncodedInt();

            _intValue = reader.ReadInt();

            _name = reader.ReadString();

            _interned = reader.ReadString(true);

            _active = reader.ReadBool();

            _weight = reader.ReadDouble();

            _crafted = reader.ReadDateTime();

            _lastUsed = reader.ReadDeltaTime();

            _duration = reader.ReadTimeSpan();

            _identifier = reader.ReadGuid();

            _encoded = reader.ReadEncodedInt();

            _price = reader.ReadDecimal();

            _small = reader.ReadByte();

            _signedSmall = reader.ReadSByte();

            _shortValue = reader.ReadShort();

            _unsignedShort = reader.ReadUShort();

            _unsignedInt = reader.ReadUInt();

            _longValue = reader.ReadLong();

            _unsignedLong = reader.ReadULong();

            _floatValue = reader.ReadFloat();

            _privateSet = reader.ReadInt();
        }
    }
}
