// <auto-generated>
//     This code was generated by the ModernUO Serialization Generator tool.
//     Version: {VERSION}
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

#pragma warning disable

namespace Server.TestContent
{
    [System.CodeDom.Compiler.GeneratedCode("ModernUO.Serialization.Generator", "{VERSION}")]
    public partial class SaveFlagsItem
    {
        private const int SerializationVersion = 0;

        public string Name
        {
            get => _name;
            set
            {
                if (value != _name)
                {
                    _name = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public int Charges
        {
            get => _charges;
            set
            {
                if (value != _charges)
                {
                    _charges = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public System.DateTime Expires
        {
            get => _expires;
            set
            {
                if (value != _expires)
                {
                    _expires = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public bool Identified
        {
            get => _identified;
            set
            {
                if (value != _identified)
                {
                    _identified = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public SaveFlagsItem(Server.Serial serial)
        {
            Serial = serial;
        }

        public virtual void Serialize(Server.IGenericWriter writer)
        {
            writer.WriteEncodedInt(SerializationVersion);

            var saveFlags = SaveFlag.None;
            if (ShouldSerializeName())
            {
                saveFlags |= SaveFlag.Name;
            }
            if (ShouldSerializeCharges())
            {
                saveFlags |= SaveFlag.Charges;
            }
            if (ShouldSerializeExpires())
            {
                saveFlags |= SaveFlag.Expires;
            }
            writer.WriteEnum(saveFlags);

            if ((saveFlags & SaveFlag.Name) != 0)
            {
                writer.Write(_name);
            }

            if ((saveFlags & SaveFlag.Charges) != 0)
            {
                writer.Write(_charges);
            }

            if ((saveFlags & SaveFlag.Expires) != 0)
            {
                writer.Write(_expires);
            }

            writer.Write(_identified);
        }

        public virtual void Deserialize(Server.IGenericReader reader)
        {
            var version = reader.ReadEncodedInt();

            var saveFlags = reader.ReadEnum<SaveFlag>();

            if ((saveFlags & SaveFlag.Name) != 0)
            {
                _name = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Charges) != 0)
            {
                _charges = reader.ReadInt();
            }
            else
            {
                _charges = ChargesDefaultValue();
            }

            if ((saveFlags & SaveFlag.Expires) != 0)
            {
                _expires = reader.ReadDateTime();
            }
            else
            {
                _expires = ExpiresDefaultValue();
            }

            _identified = reader.ReadBool();
        }

        [System.Flags]
        private enum SaveFlag
        {
            None = 0x00000000,
            Name = 0x00000001,
            Charges = 0x00000002,
            Expires = 0x00000004,
        }
    }
}
