// <auto-generated>
//     This code was generated by the ModernUO Serialization Generator tool.
//     Version: {VERSION}
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

#pragma warning disable

namespace Server.TestContent
{
    [System.CodeDom.Compiler.GeneratedCode("ModernUO.Serialization.Generator", "{VERSION}")]
    public partial class KeyValuePairItem
    {
        private const int SerializationVersion = 0;

        public System.Collections.Generic.KeyValuePair<int, string> Selected
        {
            get => _selected;
            set
            {
                if (!System.Collections.Generic.EqualityComparer<System.Collections.Generic.KeyValuePair<int, string>>.Default.Equals(value, _selected))
                {
                    _selected = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public KeyValuePairItem(Server.Serial serial)
        {
            Serial = serial;
        }

        public virtual void Serialize(Server.IGenericWriter writer)
        {
            writer.WriteEncodedInt(SerializationVersion);

            writer.Write(_selected.Key);
            writer.Write(_selected.Value);
        }

        public virtual void Deserialize(Server.IGenericReader reader)
        {
            var version = reader.ReadEncodedInt();

            int _selectedKey;
            string _selectedValue;
            _selectedKey = reader.ReadInt();
            _selectedValue = reader.ReadString();
            _selected = new System.Collections.Generic.KeyValuePair<int, string>(_selectedKey, _selectedValue);
        }
    }
}
