// <auto-generated>
//     This code was generated by the ModernUO Serialization Generator tool.
//     Version: {VERSION}
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

#pragma warning disable

namespace Server.TestContent
{
    [System.CodeDom.Compiler.GeneratedCode("ModernUO.Serialization.Generator", "{VERSION}")]
    public partial class Roster
    {
        private const int SerializationVersion = 0;

        public System.Collections.Generic.List<Server.TestContent.RosterEntry> Entries
        {
            get => _entries;
            set
            {
                if (value != _entries)
                {
                    _entries = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public void AddToEntries(Server.TestContent.RosterEntry value)
        {
            Entries.Add(value);
            Server.ISerializableExtensions.MarkDirty(this);
        }

        public void RemoveFromEntries(Server.TestContent.RosterEntry value)
        {
            Entries.Remove(value);
            Server.ISerializableExtensions.MarkDirty(this);
        }

        public void InsertIntoEntries(int index, Server.TestContent.RosterEntry value)
        {
            Entries.Insert(index, value);
            Server.ISerializableExtensions.MarkDirty(this);
        }

        public void RemoveFromEntriesAt(int index)
        {
            Entries.RemoveAt(index);
            Server.ISerializableExtensions.MarkDirty(this);
        }

        public void ClearEntries()
        {
            Entries.Clear();
            Server.ISerializableExtensions.MarkDirty(this);
        }

        public System.Collections.Generic.Dictionary<int, Server.TestContent.RosterEntry> ById
        {
            get => _byId;
            set
            {
                if (value != _byId)
                {
                    _byId = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public void AddToById(int key, Server.TestContent.RosterEntry value)
        {
            ById.Add(key, value);
            Server.ISerializableExtensions.MarkDirty(this);
        }

        public void RemoveFromById(int key)
        {
            ById.Remove(key);
            Server.ISerializableExtensions.MarkDirty(this);
        }

        public void ReplaceInById(int key, Server.TestContent.RosterEntry value)
        {
            ById[key] = value;
            Server.ISerializableExtensions.MarkDirty(this);
        }

        public void ClearById()
        {
            ById.Clear();
            Server.ISerializableExtensions.MarkDirty(this);
        }

        public Server.TestContent.RosterEntry Leader
        {
            get => _leader;
            set
            {
                if (value != _leader)
                {
                    _leader = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public Roster(Server.Serial serial)
        {
            Serial = serial;
        }

        public virtual void Serialize(Server.IGenericWriter writer)
        {
            writer.WriteEncodedInt(SerializationVersion);

            var _entriesCount = _entries?.Count ?? 0;
            writer.WriteEncodedInt(_entriesCount);
            if (_entriesCount > 0)
            {
                foreach (var _entriesEntry in _entries!)
                {
                    _entriesEntry.Serialize(writer);
                }
            }

            var _byIdCount = _byId?.Count ?? 0;
            writer.WriteEncodedInt(_byIdCount);
            if (_byIdCount > 0)
            {
                foreach (var (_byIdKey, _byIdValue) in _byId!)
                {
                    writer.Write(_byIdKey);
                    _byIdValue.Serialize(writer);
                }
            }

            _leader.Serialize(writer);
        }

        public virtual void Deserialize(Server.IGenericReader reader)
        {
            var version = reader.ReadEncodedInt();

            Server.TestContent.RosterEntry _entriesEntry;
            var _entriesCount = reader.ReadEncodedInt();
            _entries = new System.Collections.Generic.List<Server.TestContent.RosterEntry>(_entriesCount);
            for (var _entriesIndex = 0; _entriesIndex < _entriesCount; _entriesIndex++)
            {
                _entriesEntry = new Server.TestContent.RosterEntry(this);
                _entriesEntry.Deserialize(reader);
                _entries.Add(_entriesEntry);
            }

            int _byIdKey;
            Server.TestContent.RosterEntry _byIdValue;
            var _byIdCount = reader.ReadEncodedInt();
            _byId = new System.Collections.Generic.Dictionary<int, Server.TestContent.RosterEntry>(_byIdCount);
            for (var _byIdIndex = 0; _byIdIndex < _byIdCount; _byIdIndex++)
            {
                _byIdKey = reader.ReadInt();
                _byIdValue = new Server.TestContent.RosterEntry(this);
                _byIdValue.Deserialize(reader);
                if (typeof(int).IsValueType || _byIdKey != default)
                {
                    _byId.Add(_byIdKey, _byIdValue);
                }
            }

            _leader = new Server.TestContent.RosterEntry(this);
            _leader.Deserialize(reader);
        }
    }
}
