// <auto-generated>
//     This code was generated by the ModernUO Serialization Generator tool.
//     Version: {VERSION}
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

#pragma warning disable

namespace Server.TestContent
{
    [System.CodeDom.Compiler.GeneratedCode("ModernUO.Serialization.Generator", "{VERSION}")]
    public partial class CollectionsItem
    {
        private const int SerializationVersion = 0;

        public int[] Levels
        {
            get => _levels;
            set
            {
                if (value != _levels)
                {
                    _levels = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }


        public void ClearLevels()
        {
            Levels = System.Array.Empty<int>();
            Server.ISerializableExtensions.MarkDirty(this);
        }

        public System.Collections.Generic.List<int> Charges
        {
            get => _charges;
            set
            {
                if (value != _charges)
                {
                    _charges = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public void AddToCharges(int value)
        {
            Charges.Add(value);
            Server.ISerializableExtensions.MarkDirty(this);
        }

        public void RemoveFromCharges(int value)
        {
            Charges.Remove(value);
            Server.ISerializableExtensions.MarkDirty(this);
        }

        public void InsertIntoCharges(int index, int value)
        {
            Charges.Insert(index, value);
            Server.ISerializableExtensions.MarkDirty(this);
        }

        public void RemoveFromChargesAt(int index)
        {
            Charges.RemoveAt(index);
            Server.ISerializableExtensions.MarkDirty(this);
        }

        public void ClearCharges()
        {
            Charges.Clear();
            Server.ISerializableExtensions.MarkDirty(this);
        }

        public System.Collections.Generic.HashSet<string> Keywords
        {
            get => _keywords;
            set
            {
                if (value != _keywords)
                {
                    _keywords = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public void AddToKeywords(string value)
        {
            Keywords.Add(value);
            Server.ISerializableExtensions.MarkDirty(this);
        }

        public void RemoveFromKeywords(string value)
        {
            Keywords.Remove(value);
            Server.ISerializableExtensions.MarkDirty(this);
        }


        public void ClearKeywords()
        {
            Keywords.Clear();
            Server.ISerializableExtensions.MarkDirty(this);
        }

        public System.Collections.Generic.Dictionary<int, string> Labels
        {
            get => _labels;
            set
            {
                if (value != _labels)
                {
                    _labels = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public void AddToLabels(int key, string value)
        {
            Labels.Add(key, value);
            Server.ISerializableExtensions.MarkDirty(this);
        }

        public void RemoveFromLabels(int key)
        {
            Labels.Remove(key);
            Server.ISerializableExtensions.MarkDirty(this);
        }

        public void ReplaceInLabels(int key, string value)
        {
            Labels[key] = value;
            Server.ISerializableExtensions.MarkDirty(this);
        }

        public void ClearLabels()
        {
            Labels.Clear();
            Server.ISerializableExtensions.MarkDirty(this);
        }

        public CollectionsItem(Server.Serial serial)
        {
            Serial = serial;
        }

        public virtual void Serialize(Server.IGenericWriter writer)
        {
            writer.WriteEncodedInt(SerializationVersion);

            var _levelsLength = _levels?.Length ?? 0;
            writer.WriteEncodedInt(_levelsLength);
            for (var _levelsIndex = 0; _levelsIndex < _levelsLength; _levelsIndex++)
            {
                var _levelsEntry = _levels![_levelsIndex];
                writer.Write(_levelsEntry);
            }

            var _chargesCount = _charges?.Count ?? 0;
            writer.WriteEncodedInt(_chargesCount);
            if (_chargesCount > 0)
            {
                foreach (var _chargesEntry in _charges!)
                {
                    writer.Write(_chargesEntry);
                }
            }

            var _keywordsCount = _keywords?.Count ?? 0;
            writer.WriteEncodedInt(_keywordsCount);
            if (_keywordsCount > 0)
            {
                foreach (var _keywordsEntry in _keywords!)
                {
                    writer.Write(_keywordsEntry);
                }
            }

            var _labelsCount = _labels?.Count ?? 0;
            writer.WriteEncodedInt(_labelsCount);
            if (_labelsCount > 0)
            {
                foreach (var (_labelsKey, _labelsValue) in _labels!)
                {
                    writer.Write(_labelsKey);
                    writer.Write(_labelsValue);
                }
            }
        }

        public virtual void Deserialize(Server.IGenericReader reader)
        {
            var version = reader.ReadEncodedInt();

            _levels = new int[reader.ReadEncodedInt()];
            for (var _levelsIndex = 0; _levelsIndex < _levels.Length; _levelsIndex++)
            {
                var _levelsEntry = _levels![_levelsIndex];
                _levelsEntry = reader.ReadInt();
                _levels![_levelsIndex] = _levelsEntry;
            }

            int _chargesEntry;
            var _chargesCount = reader.ReadEncodedInt();
            _charges = new System.Collections.Generic.List<int>(_chargesCount);
            for (var _chargesIndex = 0; _chargesIndex < _chargesCount; _chargesIndex++)
            {
                _chargesEntry = reader.ReadInt();
                _charges.Add(_chargesEntry);
            }

            string _keywordsEntry;
            var _keywordsCount = reader.ReadEncodedInt();
            _keywords = new System.Collections.Generic.HashSet<string>(_keywordsCount);
            for (var _keywordsIndex = 0; _keywordsIndex < _keywordsCount; _keywordsIndex++)
            {
                _keywordsEntry = reader.ReadString();
                if (typeof(string).IsValueType || _keywordsEntry != default)
                {
                    _keywords.Add(_keywordsEntry);
                }
            }

            int _labelsKey;
            string _labelsValue;
            var _labelsCount = reader.ReadEncodedInt();
            _labels = new System.Collections.Generic.Dictionary<int, string>(_labelsCount);
            for (var _labelsIndex = 0; _labelsIndex < _labelsCount; _labelsIndex++)
            {
                _labelsKey = reader.ReadInt();
                _labelsValue = reader.ReadString();
                if (typeof(int).IsValueType || _labelsKey != default)
                {
                    _labels.Add(_labelsKey, _labelsValue);
                }
            }
        }
    }
}
