// <auto-generated>
//     This code was generated by the ModernUO Serialization Generator tool.
//     Version: {VERSION}
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

#pragma warning disable

namespace Server.TestContent
{
    [System.CodeDom.Compiler.GeneratedCode("ModernUO.Serialization.Generator", "{VERSION}")]
    public partial class FlaggedTimerItem
    {
        private const int SerializationVersion = 1;

        public int Count
        {
            get => _count;
            set
            {
                if (value != _count)
                {
                    _count = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public FlaggedTimerItem(Server.Serial serial)
        {
            Serial = serial;
        }

        ref struct V0Content
        {
            internal readonly int? Count;
            internal readonly System.DateTime AnchoredTimerNext;
            internal readonly System.TimeSpan AnchoredTimerDelay;
            internal readonly System.DateTime DeadlineTimerNext;
            internal readonly System.TimeSpan DeadlineTimerDelay;
            internal readonly System.DateTime DriftTimerNext;
            internal readonly System.TimeSpan DriftTimerDelay;

            [System.Flags]
            private enum V0SaveFlag
            {
                None = 0x00000000,
                Count = 0x00000001,
                AnchoredTimer = 0x00000002,
                DeadlineTimer = 0x00000004,
                DriftTimer = 0x00000008,
            }
            internal V0Content(Server.IGenericReader reader, Server.TestContent.FlaggedTimerItem entity)
            {
                var saveFlags = reader.ReadEnum<V0SaveFlag>();

                if ((saveFlags & V0SaveFlag.Count) != 0)
                {
                    Count = reader.ReadInt();
                }
                else
                {
                    Count = default;
                }

                if ((saveFlags & V0SaveFlag.AnchoredTimer) != 0)
                {
                    AnchoredTimerNext = reader.ReadAnchoredTime();
                    AnchoredTimerDelay = AnchoredTimerNext == System.DateTime.MinValue ? System.TimeSpan.MinValue : AnchoredTimerNext - Server.Core.Now;
                }
                else
                {
                    AnchoredTimerNext = System.DateTime.MinValue;
                    AnchoredTimerDelay = System.TimeSpan.MinValue;
                }

                if ((saveFlags & V0SaveFlag.DeadlineTimer) != 0)
                {
                    DeadlineTimerNext = reader.ReadDateTime();
                    DeadlineTimerDelay = DeadlineTimerNext == System.DateTime.MinValue ? System.TimeSpan.MinValue : DeadlineTimerNext - Server.Core.Now;
                }
                else
                {
                    DeadlineTimerNext = System.DateTime.MinValue;
                    DeadlineTimerDelay = System.TimeSpan.MinValue;
                }

                if ((saveFlags & V0SaveFlag.DriftTimer) != 0)
                {
                    DriftTimerNext = reader.ReadDeltaTime();
                    DriftTimerDelay = DriftTimerNext == System.DateTime.MinValue ? System.TimeSpan.MinValue : DriftTimerNext - Server.Core.Now;
                }
                else
                {
                    DriftTimerNext = System.DateTime.MinValue;
                    DriftTimerDelay = System.TimeSpan.MinValue;
                }
            }
        }

        public virtual void Serialize(Server.IGenericWriter writer)
        {
            writer.WriteEncodedInt(SerializationVersion);

            writer.Write(_count);
        }

        public virtual void Deserialize(Server.IGenericReader reader)
        {
            var version = reader.ReadEncodedInt();

            if (version == 0)
            {
                MigrateFrom(new V0Content(reader, this));
                Server.ISerializableExtensions.MarkDirty(this);
                return;
            }

            _count = reader.ReadInt();
        }
    }
}
