// <auto-generated>
//     This code was generated by the ModernUO Serialization Generator tool.
//     Version: {VERSION}
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

#pragma warning disable

namespace Server.TestContent
{
    [System.CodeDom.Compiler.GeneratedCode("ModernUO.Serialization.Generator", "{VERSION}")]
    public partial class ExtendedOwner
    {
        private const int SerializationVersion = 0;

        public System.Collections.Generic.List<Server.TestContent.DerivedEntry> ExtendedEntries
        {
            get => _extendedEntries;
            set
            {
                if (value != _extendedEntries)
                {
                    _extendedEntries = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public void AddToExtendedEntries(Server.TestContent.DerivedEntry value)
        {
            ExtendedEntries.Add(value);
            Server.ISerializableExtensions.MarkDirty(this);
        }

        public void RemoveFromExtendedEntries(Server.TestContent.DerivedEntry value)
        {
            ExtendedEntries.Remove(value);
            Server.ISerializableExtensions.MarkDirty(this);
        }

        public void InsertIntoExtendedEntries(int index, Server.TestContent.DerivedEntry value)
        {
            ExtendedEntries.Insert(index, value);
            Server.ISerializableExtensions.MarkDirty(this);
        }

        public void RemoveFromExtendedEntriesAt(int index)
        {
            ExtendedEntries.RemoveAt(index);
            Server.ISerializableExtensions.MarkDirty(this);
        }

        public void ClearExtendedEntries()
        {
            ExtendedEntries.Clear();
            Server.ISerializableExtensions.MarkDirty(this);
        }

        public ExtendedOwner(Server.Serial serial) : base(serial)
        {
        }

        public override void Serialize(Server.IGenericWriter writer)
        {
            base.Serialize(writer);

            writer.WriteEncodedInt(SerializationVersion);

            var _extendedEntriesCount = _extendedEntries?.Count ?? 0;
            writer.WriteEncodedInt(_extendedEntriesCount);
            if (_extendedEntriesCount > 0)
            {
                foreach (var _extendedEntriesEntry in _extendedEntries!)
                {
                    _extendedEntriesEntry.Serialize(writer);
                }
            }
        }

        public override void Deserialize(Server.IGenericReader reader)
        {
            base.Deserialize(reader);

            var version = reader.ReadEncodedInt();

            Server.TestContent.DerivedEntry _extendedEntriesEntry;
            var _extendedEntriesCount = reader.ReadEncodedInt();
            _extendedEntries = new System.Collections.Generic.List<Server.TestContent.DerivedEntry>(_extendedEntriesCount);
            for (var _extendedEntriesIndex = 0; _extendedEntriesIndex < _extendedEntriesCount; _extendedEntriesIndex++)
            {
                _extendedEntriesEntry = new Server.TestContent.DerivedEntry(this);
                _extendedEntriesEntry.Deserialize(reader);
                _extendedEntries.Add(_extendedEntriesEntry);
            }
        }
    }
}
