// <auto-generated>
//     This code was generated by the ModernUO Serialization Generator tool.
//     Version: {VERSION}
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

#pragma warning disable

namespace Server.TestContent
{
    [System.CodeDom.Compiler.GeneratedCode("ModernUO.Serialization.Generator", "{VERSION}")]
    public partial class BaseEntry
    {
        private const int SerializationVersion = 0;

        public virtual void MarkDirty()
        {
            Server.ISerializableExtensions.MarkDirty(_owner);
        }

        public string Label
        {
            get => _label;
            set
            {
                if (value != _label)
                {
                    _label = value;
                    MarkDirty();
                }
            }
        }

        public int Weight
        {
            get => _weight;
            set
            {
                if (value != _weight)
                {
                    _weight = value;
                    MarkDirty();
                }
            }
        }

        public virtual void Serialize(Server.IGenericWriter writer)
        {
            writer.WriteEncodedInt(SerializationVersion);

            writer.Write(_label);

            writer.Write(_weight);
        }

        public virtual void Deserialize(Server.IGenericReader reader)
        {
            var version = reader.ReadEncodedInt();

            _label = reader.ReadString();

            _weight = reader.ReadInt();
            AfterBaseDeserialization();
        }
    }
}
