// <auto-generated>
//     This code was generated by the ModernUO Serialization Generator tool.
//     Version: {VERSION}
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

#pragma warning disable

namespace Server.TestContent
{
    [System.CodeDom.Compiler.GeneratedCode("ModernUO.Serialization.Generator", "{VERSION}")]
    public partial class Owner
    {
        private const int SerializationVersion = 0;

        public System.Collections.Generic.List<Server.TestContent.BaseEntry> Entries
        {
            get => _entries;
            set
            {
                if (value != _entries)
                {
                    _entries = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public void AddToEntries(Server.TestContent.BaseEntry value)
        {
            _entries ??= new System.Collections.Generic.List<Server.TestContent.BaseEntry>();
            _entries.Add(value);
            Server.ISerializableExtensions.MarkDirty(this);
        }

        public void RemoveFromEntries(Server.TestContent.BaseEntry value)
        {
            if (_entries?.Remove(value) == true)
            {
                Server.ISerializableExtensions.MarkDirty(this);
            }
        }

        public void InsertIntoEntries(int index, Server.TestContent.BaseEntry value)
        {
            _entries ??= new System.Collections.Generic.List<Server.TestContent.BaseEntry>();
            _entries.Insert(index, value);
            Server.ISerializableExtensions.MarkDirty(this);
        }

        public void RemoveFromEntriesAt(int index)
        {
            if (_entries != null)
            {
                _entries.RemoveAt(index);
                Server.ISerializableExtensions.MarkDirty(this);
            }
        }

        public void ClearEntries()
        {
            if (_entries?.Count > 0)
            {
                _entries.Clear();
                Server.ISerializableExtensions.MarkDirty(this);
            }
        }

        public Owner(Server.Serial serial) : base(serial)
        {
        }

        public override void Serialize(Server.IGenericWriter writer)
        {
            base.Serialize(writer);

            writer.WriteEncodedInt(SerializationVersion);

            var _entriesCount = _entries?.Count ?? 0;
            writer.WriteEncodedInt(_entriesCount);
            if (_entriesCount > 0)
            {
                foreach (var _entriesEntry in _entries!)
                {
                    _entriesEntry.Serialize(writer);
                }
            }
        }

        public override void Deserialize(Server.IGenericReader reader)
        {
            base.Deserialize(reader);

            var version = reader.ReadEncodedInt();

            Server.TestContent.BaseEntry _entriesEntry;
            var _entriesCount = reader.ReadEncodedInt();
            _entries = new System.Collections.Generic.List<Server.TestContent.BaseEntry>(_entriesCount);
            for (var _entriesIndex = 0; _entriesIndex < _entriesCount; _entriesIndex++)
            {
                _entriesEntry = new Server.TestContent.BaseEntry(this);
                _entriesEntry.Deserialize(reader);
                _entries.Add(_entriesEntry);
            }
        }
    }
}
