// <auto-generated>
//     This code was generated by the ModernUO Serialization Generator tool.
//     Version: {VERSION}
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

#pragma warning disable

namespace Server.TestContent
{
    [System.CodeDom.Compiler.GeneratedCode("ModernUO.Serialization.Generator", "{VERSION}")]
    public partial class DerivedEntry
    {
        private const int SerializationVersion = 0;

        public string Script
        {
            get => _script;
            set
            {
                if (value != _script)
                {
                    _script = value;
                    MarkDirty();
                }
            }
        }

        public bool Disabled
        {
            get => _disabled;
            set
            {
                if (value != _disabled)
                {
                    _disabled = value;
                    MarkDirty();
                }
            }
        }

        public override void Serialize(Server.IGenericWriter writer)
        {
            base.Serialize(writer);

            writer.WriteEncodedInt(SerializationVersion);

            writer.Write(_script);

            writer.Write(_disabled);
        }

        public override void Deserialize(Server.IGenericReader reader)
        {
            base.Deserialize(reader);

            var version = reader.ReadEncodedInt();

            _script = reader.ReadString();

            _disabled = reader.ReadBool();
            AfterDerivedDeserialization();
        }
    }
}
