// <auto-generated>
//     This code was generated by the ModernUO Serialization Generator tool.
//     Version: {VERSION}
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

#pragma warning disable

namespace Server.TestContent
{
    [System.CodeDom.Compiler.GeneratedCode("ModernUO.Serialization.Generator", "{VERSION}")]
    public partial class FieldLinkedItem
    {
        private const int SerializationVersion = 0;

        public string Name
        {
            get => _name;
            set
            {
                if (value != _name)
                {
                    _name = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public int Charges
        {
            get => _charges;
            set
            {
                if (value != _charges)
                {
                    _charges = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public int Level
        {
            get => _level;
            set
            {
                var oldValue = _level;
                if (value != _level)
                {
                    _level = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                    OnLevelChanged(oldValue, value);
                }
            }
        }

        public int Water
        {
            get => _water;
            set
            {
                if (value != _water)
                {
                    if (!AllowWaterChange(ref value))
                    {
                        return;
                    }

                    _water = value;
                    Server.ISerializableExtensions.MarkDirty(this);
                }
            }
        }

        public FieldLinkedItem(Server.Serial serial)
        {
            Serial = serial;
        }

        public virtual void Serialize(Server.IGenericWriter writer)
        {
            writer.WriteEncodedInt(SerializationVersion);

            var saveFlags = SaveFlag.None;
            if (ShouldSerializeName())
            {
                saveFlags |= SaveFlag.Name;
            }
            if (ShouldSerializeCharges())
            {
                saveFlags |= SaveFlag.Charges;
            }
            writer.WriteEnum(saveFlags);

            if ((saveFlags & SaveFlag.Name) != 0)
            {
                writer.Write(_name);
            }

            if ((saveFlags & SaveFlag.Charges) != 0)
            {
                writer.Write(_charges);
            }

            writer.Write(_level);

            writer.Write(_water);
        }

        public virtual void Deserialize(Server.IGenericReader reader)
        {
            var version = reader.ReadEncodedInt();

            var saveFlags = reader.ReadEnum<SaveFlag>();

            if ((saveFlags & SaveFlag.Name) != 0)
            {
                _name = reader.ReadString();
            }

            if ((saveFlags & SaveFlag.Charges) != 0)
            {
                _charges = reader.ReadInt();
            }
            else
            {
                _charges = ChargesDefaultValue();
            }

            _level = reader.ReadInt();

            _water = reader.ReadInt();
        }

        [System.Flags]
        private enum SaveFlag
        {
            None = 0x00000000,
            Name = 0x00000001,
            Charges = 0x00000002,
        }
    }
}
