// <auto-generated>
//     This code was generated by the ModernUO Serialization Generator tool.
//     Version: {VERSION}
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

#pragma warning disable

namespace Server.TestContent
{
    [System.CodeDom.Compiler.GeneratedCode("ModernUO.Serialization.Generator", "{VERSION}")]
    public partial class NullableCollectionsItem
    {
        private const int SerializationVersion = 0;

        public string? Title
        {
            get => _title;
            set
            {
                if (value != _title)
                {
                    _title = value;
                    MarkDirty();
                }
            }
        }

        public System.Collections.Generic.List<int>? Charges
        {
            get => _charges;
            set
            {
                if (value != _charges)
                {
                    _charges = value;
                    MarkDirty();
                }
            }
        }

        public void AddToCharges(int value)
        {
            _charges ??= new System.Collections.Generic.List<int>();
            _charges.Add(value);
            MarkDirty();
        }

        public void RemoveFromCharges(int value)
        {
            if (_charges?.Remove(value) == true)
            {
                MarkDirty();
            }
        }

        public void InsertIntoCharges(int index, int value)
        {
            _charges ??= new System.Collections.Generic.List<int>();
            _charges.Insert(index, value);
            MarkDirty();
        }

        public void RemoveFromChargesAt(int index)
        {
            if (_charges != null)
            {
                _charges.RemoveAt(index);
                MarkDirty();
            }
        }

        public void ClearCharges()
        {
            if (_charges?.Count > 0)
            {
                _charges.Clear();
                MarkDirty();
            }
        }

        public System.Collections.Generic.HashSet<string>? Keywords
        {
            get => _keywords;
            set
            {
                if (value != _keywords)
                {
                    _keywords = value;
                    MarkDirty();
                }
            }
        }

        public void AddToKeywords(string value)
        {
            _keywords ??= new System.Collections.Generic.HashSet<string>();
            if (_keywords.Add(value))
            {
                MarkDirty();
            }
        }

        public void RemoveFromKeywords(string value)
        {
            if (_keywords?.Remove(value) == true)
            {
                MarkDirty();
            }
        }

        public void ClearKeywords()
        {
            if (_keywords?.Count > 0)
            {
                _keywords.Clear();
                MarkDirty();
            }
        }

        public System.Collections.Generic.Dictionary<int, string?>? Labels
        {
            get => _labels;
            set
            {
                if (value != _labels)
                {
                    _labels = value;
                    MarkDirty();
                }
            }
        }

        public void AddToLabels(int key, string? value)
        {
            _labels ??= new System.Collections.Generic.Dictionary<int, string>();
            if (_labels.TryAdd(key, value))
            {
                MarkDirty();
            }
        }

        public void RemoveFromLabels(int key)
        {
            if (_labels?.Remove(key) == true)
            {
                MarkDirty();
            }
        }

        public void ReplaceInLabels(int key, string? value)
        {
            _labels ??= new System.Collections.Generic.Dictionary<int, string>();
            _labels[key] = value;
            MarkDirty();
        }

        public void ClearLabels()
        {
            if (_labels?.Count > 0)
            {
                _labels.Clear();
                MarkDirty();
            }
        }

        public System.Collections.Generic.SortedSet<string>? Names
        {
            get => _names;
            set
            {
                if (value != _names)
                {
                    _names = value;
                    MarkDirty();
                }
            }
        }

        public void AddToNames(string value)
        {
            _names ??= new System.Collections.Generic.SortedSet<string>(new Server.TestContent.CaseInsensitiveComparer());
            if (_names.Add(value))
            {
                MarkDirty();
            }
        }

        public void RemoveFromNames(string value)
        {
            if (_names?.Remove(value) == true)
            {
                MarkDirty();
            }
        }

        public void ClearNames()
        {
            if (_names?.Count > 0)
            {
                _names.Clear();
                MarkDirty();
            }
        }

        public string?[]? Aliases
        {
            get => _aliases;
            set
            {
                if (value != _aliases)
                {
                    _aliases = value;
                    MarkDirty();
                }
            }
        }


        public void ClearAliases()
        {
            Aliases = System.Array.Empty<string?>();
            MarkDirty();
        }

        public NullableCollectionsItem(Server.Serial serial)
        {
            Serial = serial;
        }

        public virtual void Serialize(Server.IGenericWriter writer)
        {
            writer.WriteEncodedInt(SerializationVersion);

            writer.Write(_title);

            var _chargesCount = _charges?.Count ?? 0;
            writer.WriteEncodedInt(_chargesCount);
            if (_chargesCount > 0)
            {
                foreach (var _chargesEntry in _charges!)
                {
                    writer.Write(_chargesEntry);
                }
            }

            var _keywordsCount = _keywords?.Count ?? 0;
            writer.WriteEncodedInt(_keywordsCount);
            if (_keywordsCount > 0)
            {
                foreach (var _keywordsEntry in _keywords!)
                {
                    writer.Write(_keywordsEntry);
                }
            }

            var _labelsCount = _labels?.Count ?? 0;
            writer.WriteEncodedInt(_labelsCount);
            if (_labelsCount > 0)
            {
                foreach (var (_labelsKey, _labelsValue) in _labels!)
                {
                    writer.Write(_labelsKey);
                    writer.Write(_labelsValue);
                }
            }

            var _namesCount = _names?.Count ?? 0;
            writer.WriteEncodedInt(_namesCount);
            if (_namesCount > 0)
            {
                foreach (var _namesEntry in _names!)
                {
                    writer.Write(_namesEntry);
                }
            }

            var _aliasesLength = _aliases?.Length ?? 0;
            writer.WriteEncodedInt(_aliasesLength);
            for (var _aliasesIndex = 0; _aliasesIndex < _aliasesLength; _aliasesIndex++)
            {
                var _aliasesEntry = _aliases![_aliasesIndex];
                writer.Write(_aliasesEntry);
            }
        }

        public virtual void Deserialize(Server.IGenericReader reader)
        {
            var version = reader.ReadEncodedInt();

            _title = reader.ReadString();

            int _chargesEntry;
            var _chargesCount = reader.ReadEncodedInt();
            _charges = new System.Collections.Generic.List<int>(_chargesCount);
            for (var _chargesIndex = 0; _chargesIndex < _chargesCount; _chargesIndex++)
            {
                _chargesEntry = reader.ReadInt();
                _charges.Add(_chargesEntry);
            }

            string _keywordsEntry;
            var _keywordsCount = reader.ReadEncodedInt();
            _keywords = new System.Collections.Generic.HashSet<string>(_keywordsCount);
            for (var _keywordsIndex = 0; _keywordsIndex < _keywordsCount; _keywordsIndex++)
            {
                _keywordsEntry = reader.ReadString();
                if (typeof(string).IsValueType || _keywordsEntry != default)
                {
                    _keywords.Add(_keywordsEntry);
                }
            }

            int _labelsKey;
            string _labelsValue;
            var _labelsCount = reader.ReadEncodedInt();
            _labels = new System.Collections.Generic.Dictionary<int, string>(_labelsCount);
            for (var _labelsIndex = 0; _labelsIndex < _labelsCount; _labelsIndex++)
            {
                _labelsKey = reader.ReadInt();
                _labelsValue = reader.ReadString();
                if (typeof(int).IsValueType || _labelsKey != default)
                {
                    _labels.Add(_labelsKey, _labelsValue);
                }
            }

            string _namesEntry;
            var _namesCount = reader.ReadEncodedInt();
            _names = new System.Collections.Generic.SortedSet<string>(new Server.TestContent.CaseInsensitiveComparer());
            for (var _namesIndex = 0; _namesIndex < _namesCount; _namesIndex++)
            {
                _namesEntry = reader.ReadString();
                if (typeof(string).IsValueType || _namesEntry != default)
                {
                    _names.Add(_namesEntry);
                }
            }

            _aliases = new string[reader.ReadEncodedInt()];
            for (var _aliasesIndex = 0; _aliasesIndex < _aliases.Length; _aliasesIndex++)
            {
                var _aliasesEntry = _aliases![_aliasesIndex];
                _aliasesEntry = reader.ReadString();
                _aliases![_aliasesIndex] = _aliasesEntry;
            }
        }
    }
}
